import { PageTitle, formatMoney } from "@/components/arcway/primitives";
import { EmptyPanel, MetricCard } from "@/components/arcway/primitives";
import { trpc } from "@/lib/trpc";
import { BarChart3, CircleCheck, ShieldAlert, Timer } from "lucide-react";

export default function Analytics() {
  const query = trpc.trades.dashboard.useQuery(undefined, { retry: false }); const data = query.data; const total = (data?.verification.approved ?? 0) + (data?.verification.underReview ?? 0) + (data?.verification.blocked ?? 0); const completion = total ? Math.round(((data?.verification.approved ?? 0) / total) * 100) : 0;
  return <div className="mx-auto max-w-[1540px] animate-enter"><PageTitle eyebrow="Portfolio analytics" title="Assurance performance, made visible." description="Track the quality of your operating evidence, review throughput, and exposure across the platform." />{total === 0 ? <EmptyPanel title="Analytics will develop with the portfolio" description="As Trade Twins are submitted, reviewed, and released, this area will summarize assurance throughput and risk concentration." /> : <><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><MetricCard label="Verified rate" value={`${completion}%`} helper={`${data?.verificationThroughput ?? 0} final assurance decisions`} icon={<CircleCheck className="h-5 w-5" />} tone="green" /><MetricCard label="Open exposure" value={formatMoney(data?.valueAtRisk ?? 0)} helper="Value across active Trade Twins" icon={<ShieldAlert className="h-5 w-5" />} tone="amber" /><MetricCard label="Review queue" value={data?.verification.underReview ?? 0} helper="Trades requiring a reviewer decision" icon={<Timer className="h-5 w-5" />} tone="blue" /><MetricCard label="Open exceptions" value={data?.exceptionVolume ?? 0} helper="Outstanding cross-source conflicts" icon={<BarChart3 className="h-5 w-5" />} tone="rose" /></div><div className="panel mt-5 p-6"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-slate-100">Assurance state distribution</p><p className="mt-1 text-xs text-slate-500">Current portfolio by decision stage</p></div><p className="font-mono text-xs text-slate-500">LIVE VIEW</p></div><div className="mt-8 grid gap-4 md:grid-cols-3">{[["Approved", data?.verification.approved ?? 0, "bg-emerald-400"], ["Awaiting review", data?.verification.underReview ?? 0, "bg-amber-400"], ["Blocked / rejected", data?.verification.blocked ?? 0, "bg-rose-400"]].map(([label, count, color]) => <div key={String(label)} className="rounded-xl border border-white/[0.07] bg-white/[0.025] p-4"><div className="flex items-center justify-between"><span className="text-sm text-slate-300">{label}</span><span className="text-lg font-semibold text-slate-100">{count}</span></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-white/[0.06]"><div className={`h-full rounded-full ${color}`} style={{ width: `${total ? (Number(count) / total) * 100 : 0}%` }} /></div></div>)}</div></div></>}</div>;
}
