import { PageTitle, StatusBadge } from "@/components/arcway/primitives";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { ArrowDownUp, CheckCircle2, CircleDotDashed, GitCompareArrows, History, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

const authorityRank: Record<string, number> = { canonical: 0, authoritative: 1, supporting: 2, conflicting: 3 };

export default function CanonicalizationCenter() {
  const { user } = useAuth();
  const trades = trpc.trades.list.useQuery(undefined, { retry: false });
  const isReviewer = user?.role === "reviewer";
  const [tradeId, setTradeId] = useState<number | null>(null);
  const activeId = tradeId ?? trades.data?.[0]?.id ?? null;
  const workspace = trpc.trades.get.useQuery({ tradeId: activeId ?? 0 }, { enabled: Boolean(activeId), retry: false });
  const fields = workspace.data?.fields ?? [];
  const grouped = useMemo(() => Object.entries(fields.reduce<Record<string, typeof fields>>((groups, field) => { (groups[field.fieldName] ||= []).push(field); return groups; }, {})).map(([name, records]) => [name, records.sort((a, b) => authorityRank[a.authority] - authorityRank[b.authority] || Number(b.confidence) - Number(a.confidence))] as const), [fields]);
  const [resolutionField, setResolutionField] = useState("");
  const [selectedEvidenceId, setSelectedEvidenceId] = useState("");
  const [selectedValue, setSelectedValue] = useState("");
  const [rationale, setRationale] = useState("");
  const utils = trpc.useUtils();
  const impact = trpc.operations.canonicalization.impact.useQuery({ tradeId: activeId ?? 0, fieldName: resolutionField || "field", selectedValue: selectedValue || undefined }, { enabled: Boolean(isReviewer && activeId && resolutionField), retry: false });
  const resolve = trpc.operations.canonicalization.resolve.useMutation({ onSuccess: () => { toast.success("Canonical field decision retained with conflict lineage"); setResolutionField(""); setSelectedEvidenceId(""); setSelectedValue(""); setRationale(""); if (activeId) utils.trades.get.invalidate({ tradeId: activeId }); }, onError: error => toast.error(error.message) });
  const resolutionRecords = resolutionField ? (grouped.find(([field]) => field === resolutionField)?.[1] ?? []) : [];
  const data = workspace.data;

  return <div className="mx-auto max-w-[1540px] animate-enter"><PageTitle eyebrow="Canonicalization & lineage" title="See why each Trade Twin field is trusted." description="ARCWAY retains conflicting values rather than silently overwriting source truth. Reviewer decisions preserve selected evidence, all competing sources, rationale, policy context, and superseded history." />
    <div className="mt-6 grid gap-5 xl:grid-cols-[250px_1fr]"><aside className="panel h-fit overflow-hidden"><div className="border-b border-white/[0.07] px-4 py-3"><p className="text-xs font-semibold uppercase tracking-[0.13em] text-slate-500">Trade Twin</p></div>{trades.data?.map(trade => <button key={trade.id} onClick={() => setTradeId(trade.id)} className={`w-full border-b border-white/[0.05] px-4 py-4 text-left ${activeId === trade.id ? "bg-blue-500/[0.08]" : "hover:bg-white/[0.03]"}`}><p className="font-mono text-[10px] text-blue-300">{trade.reference}</p><p className="mt-1 text-xs text-slate-300">{trade.sellerName} → {trade.buyerName}</p></button>)}</aside>
      <section className="space-y-5"><div className="grid gap-4 md:grid-cols-3"><Explainer icon={ShieldCheck} title="Source hierarchy" text="Canonical → authoritative → supporting → conflicting" /><Explainer icon={GitCompareArrows} title="Conflict lineage" text="Disputed values remain linked to their source record" /><Explainer icon={History} title="Historical reconstruction" text="Revisions and decisions are never silently discarded" /></div>
        {isReviewer && resolutionField && data && <div className="panel p-6"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-semibold text-slate-100">Resolve canonical field: <span className="font-mono text-blue-200">{resolutionField}</span></p><p className="mt-1 text-xs text-slate-500">Selecting a source creates a new active decision and automatically retains the previous decision as superseded history.</p></div><Button onClick={() => setResolutionField("")} variant="outline" className="border-white/[0.1] text-xs text-slate-400">Cancel</Button></div><div className="mt-4 grid gap-3 lg:grid-cols-2"><select aria-label="Evidence source to select" value={selectedEvidenceId} onChange={event => { setSelectedEvidenceId(event.target.value); const record = resolutionRecords.find(item => item.id === Number(event.target.value)); if (record) setSelectedValue(record.fieldValue); }} className="h-10 rounded-md border border-white/[0.1] bg-[#111827] px-3 text-sm text-slate-200"><option value="">Select evidence source…</option>{resolutionRecords.map(record => <option value={record.id} key={record.id}>{record.authority} · {record.fieldValue}</option>)}</select><Input value={selectedValue} onChange={event => setSelectedValue(event.target.value)} placeholder="Canonical selected value" className="border-white/[0.1] bg-[#111827] text-slate-200 placeholder:text-slate-600" /></div><ImpactPreview impact={impact.data} loading={impact.isLoading} /><Textarea value={rationale} onChange={event => setRationale(event.target.value)} placeholder="Decision rationale, source authority reasoning, and policy context…" className="mt-3 min-h-24 border-white/[0.1] bg-[#111827] text-slate-200 placeholder:text-slate-600" /><Button disabled={!selectedEvidenceId || !selectedValue || rationale.length < 12 || resolve.isPending} onClick={() => resolve.mutate({ tradeId: data.trade.id, fieldName: resolutionField, selectedEvidenceFieldId: Number(selectedEvidenceId), selectedValue, conflictingEvidenceFieldIds: resolutionRecords.filter(record => record.id !== Number(selectedEvidenceId)).map(record => record.id), rationale, policyContext: { authorityModel: "ARCWAY source hierarchy", resolutionScope: "Trade Twin material field", impactPreview: impact.data } })} className="mt-3 bg-blue-500 text-white hover:bg-blue-400"><CheckCircle2 className="mr-1.5 h-4 w-4" />Retain canonical decision</Button></div>}
        <div className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-white/[0.07] px-6 py-4"><div><p className="text-sm font-semibold text-slate-100">Field resolver</p><p className="mt-1 text-xs text-slate-500">Highest-ranked source is shown first; each field’s reviewer decision and competing source values remain visible.</p></div><ArrowDownUp className="h-4 w-4 text-blue-300" /></div>{grouped.length ? <div className="divide-y divide-white/[0.06]">{grouped.map(([fieldName, records]) => { const activeResolution = data?.canonicalResolutions.find(resolution => resolution.fieldName === fieldName && resolution.active === 1); const historicalResolutions = data?.canonicalResolutions.filter(resolution => resolution.fieldName === fieldName && resolution.active !== 1) ?? []; return <div key={fieldName} className="p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-mono text-xs text-blue-200">{fieldName}</p><p className="mt-1 text-[10px] uppercase tracking-[0.12em] text-slate-600">{records.length} retained source{records.length === 1 ? "" : "s"}</p></div>{isReviewer && <Button onClick={() => { setResolutionField(fieldName); setSelectedEvidenceId(String(records[0]?.id ?? "")); setSelectedValue(records[0]?.fieldValue ?? ""); setRationale(""); }} variant="outline" className="h-8 border-blue-400/20 bg-blue-400/[0.04] text-xs text-blue-200 hover:bg-blue-400/[0.1]">{activeResolution ? "Revise decision" : "Resolve field"}</Button>}</div>
          {activeResolution && <div className="mt-4 rounded-lg border border-emerald-400/20 bg-emerald-400/[0.04] p-4"><div className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-300" /><p className="text-sm font-medium text-emerald-100">Canonical decision: {activeResolution.selectedValue}</p></div><p className="mt-2 text-xs leading-5 text-slate-300">{activeResolution.rationale}</p><p className="mt-2 text-[11px] text-slate-500">Resolved {formatStamp(activeResolution.resolvedAt)} · selected evidence #{activeResolution.selectedEvidenceFieldId ?? "manual"} · {historicalResolutions.length} superseded decision{historicalResolutions.length === 1 ? "" : "s"} retained</p></div>}
          <div className="mt-4 grid gap-3 lg:grid-cols-2">{records.map((record, index) => <div key={record.id} className={`rounded-lg border p-4 ${record.authority === "conflicting" ? "border-amber-400/20 bg-amber-400/[0.035]" : index === 0 ? "border-blue-400/20 bg-blue-400/[0.04]" : "border-white/[0.07] bg-white/[0.025]"}`}><div className="flex items-start justify-between gap-3"><p className="text-sm font-medium text-slate-100">{record.fieldValue}</p><StatusBadge status={record.authority} /></div><p className="mt-2 text-xs text-slate-500">Confidence {Number(record.confidence).toFixed(2)} · {record.modelVersion || "source-recorded"}</p><p className="mt-1 text-xs text-slate-600">{record.sourceLocation ? "Source location retained" : "Source location not specified"} · extracted {formatStamp(record.extractedAt)}</p></div>)}</div></div>; })}</div> : <div className="px-6 py-16 text-center"><CircleDotDashed className="mx-auto h-6 w-6 text-slate-600" /><p className="mt-3 text-sm text-slate-500">No extracted fields have been retained for this Trade Twin yet.</p></div>}</div>
        <div className="panel p-6"><p className="text-sm font-semibold text-slate-100">Revision lineage</p><div className="mt-5 space-y-3">{data?.revisions.length ? data.revisions.map(revision => <div key={revision.id} className="flex gap-3 rounded-lg border border-white/[0.07] bg-white/[0.025] p-4"><History className="mt-0.5 h-4 w-4 text-blue-300" /><div><p className="text-sm text-slate-200">v{revision.version} · {revision.reason}</p><p className="mt-1 text-xs text-slate-500">{revision.source} · observed {formatStamp(revision.observedAt)} · recorded {formatStamp(revision.recordedAt)}</p></div></div>) : <p className="text-sm text-slate-500">No retained state revisions yet.</p>}</div></div>
      </section>
    </div>
  </div>;
}

function Explainer({ icon: Icon, title, text }: { icon: typeof ShieldCheck; title: string; text: string }) { return <div className="panel p-5"><Icon className="h-4 w-4 text-blue-300" /><p className="mt-4 text-sm font-semibold text-slate-200">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div>; }
function ImpactPreview({ impact, loading }: { impact: { summary: string; items: Array<{ category: string; target: string; severity: string; reason: string; action: string }> } | undefined; loading: boolean }) { return <div className="mt-4 rounded-xl border border-amber-400/20 bg-amber-400/[0.035] p-4"><div className="flex items-center gap-2"><GitCompareArrows className="h-4 w-4 text-amber-300" /><p className="text-xs font-semibold uppercase tracking-[0.13em] text-amber-100">Change impact before resolution</p></div><p className="mt-2 text-xs leading-5 text-slate-300">{loading ? "Evaluating retained documents, obligations, shipment milestones, and release gates…" : impact?.summary || "Select a field to see deterministic downstream artifacts that require review."}</p>{impact?.items.length ? <div className="mt-3 grid gap-2 lg:grid-cols-2">{impact.items.map(item => <div key={`${item.category}-${item.target}`} className="rounded-lg border border-white/[0.08] bg-[#0b1220]/70 p-3"><div className="flex items-center justify-between gap-2"><p className="text-xs font-medium text-slate-200">{item.target}</p><span className={`rounded px-1.5 py-0.5 text-[9px] font-semibold uppercase tracking-[0.1em] ${item.severity === "blocker" ? "bg-rose-400/10 text-rose-200" : item.severity === "warning" ? "bg-amber-400/10 text-amber-200" : "bg-blue-400/10 text-blue-200"}`}>{item.severity}</span></div><p className="mt-1 text-[11px] leading-4 text-slate-500">{item.reason}</p><p className="mt-2 text-[11px] leading-4 text-slate-300">{item.action}</p></div>)}</div> : null}</div>; }
function formatStamp(value: Date | null | undefined) { return value ? new Date(value).toLocaleString() : "Not recorded"; }
