import { EmptyPanel, PageTitle, StatusBadge } from "@/components/arcway/primitives";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { AlertTriangle, CheckCircle2, FileSearch, Filter, GitCompareArrows, History, Link2, ScanLine } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

const documentStatuses = ["all", "pending", "uploaded", "under review", "verified", "rejected"] as const;
type DocumentStatusFilter = typeof documentStatuses[number];

export default function DocumentWorkbench() {
  const trades = trpc.trades.list.useQuery(undefined, { retry: false });
  const [tradeId, setTradeId] = useState<number | null>(null);
  const activeId = tradeId ?? trades.data?.[0]?.id ?? null;
  const workspace = trpc.trades.get.useQuery({ tradeId: activeId ?? 0 }, { enabled: Boolean(activeId), retry: false });
  const [documentId, setDocumentId] = useState<number | null>(null);
  const [statusFilter, setStatusFilter] = useState<DocumentStatusFilter>("all");
  const [comparisonVersionId, setComparisonVersionId] = useState<number | null>(null);
  const [correctionJson, setCorrectionJson] = useState("");
  const [reviewerNotes, setReviewerNotes] = useState("");
  const data = workspace.data;
  const visibleDocuments = useMemo(() => data?.documents.filter(document => statusFilter === "all" || document.status === statusFilter) ?? [], [data?.documents, statusFilter]);
  const activeDocument = visibleDocuments.find(item => item.id === (documentId ?? visibleDocuments[0]?.id)) ?? visibleDocuments[0];
  const extracted = (activeDocument?.extractedData ?? {}) as Record<string, unknown>;
  const fieldEntries = Object.entries(extracted).filter(([key]) => !["issues", "confidence"].includes(key));
  const versions = data?.documentVersions.filter(item => item.documentId === activeDocument?.id) ?? [];
  const comparisonVersion = versions.find(version => version.id === comparisonVersionId) ?? versions[versions.length - 1];
  const versionFields = (comparisonVersion?.extractedData ?? {}) as Record<string, unknown>;
  const diffKeys = Array.from(new Set([...Object.keys(versionFields), ...Object.keys(extracted)])).filter(key => !["issues", "confidence"].includes(key));
  const linkedExceptions = data?.exceptions.filter(exception => exception.documentId === activeDocument?.id) ?? [];
  const utils = trpc.useUtils();
  const correctExtraction = trpc.operations.documents.correctExtraction.useMutation({ onSuccess: () => { toast.success("Structured extraction correction retained with reviewer note"); if (activeId) utils.trades.get.invalidate({ tradeId: activeId }); }, onError: error => toast.error(error.message) });

  useEffect(() => { setCorrectionJson(JSON.stringify(activeDocument?.extractedData ?? {}, null, 2)); setReviewerNotes(""); setComparisonVersionId(null); }, [activeDocument?.id]);
  useEffect(() => { setDocumentId(null); }, [statusFilter]);

  if (!trades.data?.length) return <div className="mx-auto max-w-[1540px] animate-enter"><PageTitle eyebrow="Document Workbench" title="Evidence, structured fields, and issues in one review surface." description="Inspect issued evidence, source-derived data, and cross-document conflicts without losing provenance." /><EmptyPanel title="No Trade Twins available" description="Create or reconstruct a Trade Twin before reviewing evidence in the document workbench." /></div>;

  return <div className="mx-auto max-w-[1540px] animate-enter">
    <PageTitle eyebrow="Document Workbench" title="Evidence, structured fields, and issues in one review surface." description="Filter exact document workflow states, inspect immutable source versions, link evidence to its exceptions, and correct structured fields with retained rationale." />
    <div className="mt-6 grid gap-5 xl:grid-cols-[250px_1.05fr_1fr]">
      <aside className="panel h-fit overflow-hidden"><div className="border-b border-white/[0.07] px-4 py-3"><p className="text-xs font-semibold uppercase tracking-[0.13em] text-slate-500">Trade Twin</p></div><div className="max-h-[680px] overflow-y-auto">{trades.data.map(trade => <button key={trade.id} onClick={() => { setTradeId(trade.id); setDocumentId(null); }} className={`w-full border-b border-white/[0.05] px-4 py-4 text-left transition-colors ${activeId === trade.id ? "bg-blue-500/[0.09]" : "hover:bg-white/[0.035]"}`}><p className="font-mono text-[10px] text-blue-300">{trade.reference}</p><p className="mt-1 text-xs font-medium text-slate-200">{trade.sellerName} → {trade.buyerName}</p><p className="mt-1 text-[11px] text-slate-500">{trade.commodity}</p></button>)}</div></aside>
      <section className="panel overflow-hidden"><div className="border-b border-white/[0.07] px-5 py-4"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-slate-100">Source document queue</p><p className="mt-1 text-xs text-slate-500">Immutable issued evidence and source history</p></div><FileSearch className="h-4 w-4 text-blue-300" /></div><label className="mt-3 flex items-center gap-2 text-xs text-slate-500"><Filter className="h-3.5 w-3.5" />Exact workflow state<select aria-label="Filter documents by exact status" value={statusFilter} onChange={event => setStatusFilter(event.target.value as DocumentStatusFilter)} className="ml-auto h-8 rounded-md border border-white/[0.1] bg-[#111827] px-2 text-xs text-slate-200">{documentStatuses.map(status => <option key={status} value={status}>{status === "all" ? "All statuses" : status}</option>)}</select></label></div>
        <div className="divide-y divide-white/[0.06]">{visibleDocuments.length ? visibleDocuments.map(document => <button key={document.id} onClick={() => setDocumentId(document.id)} className={`flex w-full items-start gap-3 px-5 py-4 text-left transition-colors ${activeDocument?.id === document.id ? "bg-blue-500/[0.06]" : "hover:bg-white/[0.025]"}`}><div className="mt-0.5 grid h-8 w-8 place-items-center rounded-lg bg-white/[0.04]"><ScanLine className="h-4 w-4 text-slate-400" /></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="text-sm font-medium text-slate-200">{document.documentType}</p><StatusBadge status={document.status} /></div><p className="mt-1 truncate text-xs text-slate-500">{document.fileName || "Awaiting source evidence"}</p>{Array.isArray(document.inconsistencies) && document.inconsistencies.length > 0 && <p className="mt-2 flex items-center gap-1 text-xs text-amber-300"><AlertTriangle className="h-3.5 w-3.5" />{document.inconsistencies.length} detected issue{document.inconsistencies.length === 1 ? "" : "s"}</p>}</div></button>) : <p className="px-5 py-12 text-center text-sm text-slate-500">No documents match the selected workflow state.</p>}</div>
      </section>
      <section className="space-y-5">
        <div className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-white/[0.07] px-5 py-4"><div><p className="text-sm font-semibold text-slate-100">Structured evidence</p><p className="mt-1 text-xs text-slate-500">Field values retain their document provenance</p></div><GitCompareArrows className="h-4 w-4 text-blue-300" /></div><div className="divide-y divide-white/[0.06]">{fieldEntries.length ? fieldEntries.map(([field, value]) => { const flagged = Array.isArray(activeDocument?.inconsistencies) && activeDocument.inconsistencies.some(issue => String(issue).toLowerCase().includes(field.toLowerCase())); return <div key={field} className="flex items-start justify-between gap-4 px-5 py-3"><div><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-slate-500">{field.replace(/([A-Z])/g, " $1")}</p><p className={`mt-1 text-sm ${flagged ? "text-amber-300" : "text-slate-200"}`}>{String(value || "—")}</p></div>{flagged ? <AlertTriangle className="mt-1 h-4 w-4 text-amber-300" /> : <CheckCircle2 className="mt-1 h-4 w-4 text-emerald-300" />}</div>; }) : <p className="px-5 py-12 text-center text-sm text-slate-500">Select an uploaded document to inspect extracted evidence.</p>}</div></div>
        <div className="panel p-5"><div className="flex items-center gap-2"><Link2 className="h-4 w-4 text-blue-300" /><p className="text-sm font-semibold text-slate-100">Explicit evidence links</p></div><p className="mt-1 text-xs text-slate-500">Every exception created from this source remains directly attached to this document record.</p><div className="mt-3 space-y-2">{linkedExceptions.length ? linkedExceptions.map(exception => <div key={exception.id} className="rounded-lg border border-amber-400/15 bg-amber-400/[0.04] p-3"><div className="flex justify-between gap-3"><p className="text-xs font-medium text-amber-100">{exception.title}</p><StatusBadge status={exception.status} /></div><p className="mt-1 text-[11px] leading-5 text-slate-400">{exception.detail}</p></div>) : <p className="rounded-lg border border-dashed border-white/[0.1] p-3 text-xs text-slate-500">No exception is currently linked to this evidence record.</p>}</div></div>
        <div className="panel p-5"><p className="text-sm font-semibold text-slate-100">Reviewer correction</p><p className="mt-1 text-xs text-slate-500">Corrected fields remain linked to this source record and require a retained reviewer rationale.</p><Textarea value={correctionJson} onChange={event => setCorrectionJson(event.target.value)} className="mt-4 min-h-36 border-white/[0.1] bg-[#111827] font-mono text-xs text-slate-200" /><Textarea value={reviewerNotes} onChange={event => setReviewerNotes(event.target.value)} placeholder="Reason for the correction and evidence reviewed…" className="mt-3 min-h-20 border-white/[0.1] bg-[#111827] text-xs text-slate-200 placeholder:text-slate-600" /><Button disabled={!activeDocument || !reviewerNotes || correctExtraction.isPending} onClick={() => { try { correctExtraction.mutate({ documentId: activeDocument!.id, extractedData: JSON.parse(correctionJson), reviewerNotes }); } catch { toast.error("Structured evidence must be valid JSON before it can be retained."); } }} className="mt-3 bg-blue-500 text-white hover:bg-blue-400">Retain extraction correction</Button></div>
        <div className="panel p-5"><div className="flex items-center gap-2"><History className="h-4 w-4 text-blue-300" /><p className="text-sm font-semibold text-slate-100">Version diff & provenance</p></div><p className="mt-1 text-xs text-slate-500">Compare the selected immutable source snapshot against current structured evidence before changing a canonical field.</p>{versions.length ? <><select aria-label="Immutable version to compare" value={comparisonVersion?.id ?? ""} onChange={event => setComparisonVersionId(Number(event.target.value))} className="mt-3 h-9 w-full rounded-md border border-white/[0.1] bg-[#111827] px-3 text-xs text-slate-200">{versions.map(version => <option value={version.id} key={version.id}>v{version.version} · {version.fileName} · {new Date(version.createdAt).toLocaleString()}</option>)}</select><div className="mt-3 space-y-2">{diffKeys.map(field => { const previous = versionFields[field]; const current = extracted[field]; const changed = String(previous ?? "") !== String(current ?? ""); return <div key={field} className={`grid grid-cols-2 gap-2 rounded-lg border p-3 ${changed ? "border-amber-400/20 bg-amber-400/[0.03]" : "border-white/[0.07] bg-white/[0.02]"}`}><div><p className="text-[9px] font-semibold uppercase tracking-[0.12em] text-slate-500">v{comparisonVersion?.version} source</p><p className="mt-1 break-words text-xs text-slate-400">{String(previous ?? "—")}</p></div><div><p className="text-[9px] font-semibold uppercase tracking-[0.12em] text-slate-500">Current field</p><p className={`mt-1 break-words text-xs ${changed ? "text-amber-200" : "text-slate-200"}`}>{String(current ?? "—")}</p></div></div>; })}</div></> : <p className="mt-3 text-xs leading-5 text-slate-500">The active record is the only available source snapshot. A second upload will create an immutable version for comparison.</p>}</div>
      </section>
    </div>
  </div>;
}
