import { EmptyPanel, PageTitle } from "@/components/arcway/primitives";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { BadgeCheck, Braces, GitMerge, ShieldCheck, Sparkles } from "lucide-react";
import { useState } from "react";

type Proposal = { left: { id: number; legalName: string; countryCode: string }; right: { id: number; legalName: string; countryCode: string }; confidence: number; signals: string[]; disposition: "review_required" };

export default function EntityResolutionCenter() {
  const { user } = useAuth(); const reviewer = user?.role === "reviewer"; const proposals = trpc.operations.masters.entityResolutionPreview.useQuery(undefined, { enabled: reviewer, retry: false }); const utils = trpc.useUtils(); const confirm = trpc.operations.masters.confirmEntityAlias.useMutation({ onSuccess: async () => { await Promise.all([utils.operations.masters.entityResolutionPreview.invalidate(), utils.operations.masters.list.invalidate()]); setOpen(null); setRationale(""); } }); const [open, setOpen] = useState<string | null>(null); const [rationale, setRationale] = useState(""); const rows = (proposals.data ?? []) as Proposal[];
  if (!reviewer) return <div className="mx-auto max-w-[1100px]"><PageTitle eyebrow="Entity resolution" title="Reviewer access required" description="Counterparty alias proposals expose organization master data and are intentionally restricted to Reviewers." /><div className="mt-6"><EmptyPanel title="Entity resolution is Reviewer-controlled" description="Ask a Reviewer to assess a deterministic proposal. ARCWAY never silently merges master records." /></div></div>;
  return <div className="mx-auto max-w-[1240px] animate-enter"><PageTitle eyebrow="Counterparty entity resolution" title="Review aliases without merging the master record." description="ARCWAY proposes only high-confidence, same-country retained master variants. Confirmation creates an immutable successor with a trading alias; it does not merge counterparties or alter trade history." />
    <div className="mt-6 grid gap-4 md:grid-cols-3"><Metric icon={Sparkles} label="Review proposals" value={rows.length} text="High-confidence retained variants" tone="blue" /><Metric icon={GitMerge} label="Automatic merges" value="0" text="Every alias requires a Reviewer" tone="amber" /><Metric icon={ShieldCheck} label="Master safety" value="Versioned" text="Confirmation creates a successor" tone="emerald" /></div>
    <section className="mt-6 panel overflow-hidden"><div className="border-b border-white/[0.07] px-5 py-4"><p className="text-sm font-semibold text-slate-100">Retained master proposals</p><p className="mt-1 text-xs leading-5 text-slate-500">Signals describe the deterministic comparison. They are not an identity determination, compliance opinion, or authorization to merge records.</p></div>{proposals.isLoading ? <div className="p-8 text-sm text-slate-500">Comparing active retained counterparties…</div> : !rows.length ? <div className="p-6"><EmptyPanel title="No high-confidence aliases need review" description="ARCWAY will show only active, same-country masters that meet the deterministic proposal threshold." /></div> : <div className="divide-y divide-white/[0.06]">{rows.map(proposal => { const leftKey = `${proposal.left.id}-${proposal.right.id}-left`; const rightKey = `${proposal.left.id}-${proposal.right.id}-right`; return <article key={`${proposal.left.id}-${proposal.right.id}`} className="p-5"><div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_auto_minmax(0,1fr)] lg:items-center"><Master name={proposal.left.legalName} country={proposal.left.countryCode} /><div className="flex flex-col items-center gap-2"><span className="rounded-full border border-blue-400/20 bg-blue-400/[0.06] px-3 py-1 text-xs font-semibold text-blue-200">{Math.round(proposal.confidence * 100)}% signal</span><Braces className="h-4 w-4 text-slate-600" /></div><Master name={proposal.right.legalName} country={proposal.right.countryCode} /></div><div className="mt-4 flex flex-wrap gap-2">{proposal.signals.map(signal => <span key={signal} className="rounded-md border border-white/[0.08] bg-white/[0.025] px-2 py-1 text-[11px] text-slate-400">{signal}</span>)}</div><div className="mt-5 grid gap-3 md:grid-cols-2"><AliasAction open={open === leftKey} onToggle={() => { setOpen(open === leftKey ? null : leftKey); setRationale(""); }} sourceName={proposal.left.legalName} alias={proposal.right.legalName} disabled={confirm.isPending} rationale={rationale} onRationale={setRationale} onConfirm={() => confirm.mutate({ sourceId: proposal.left.id, alias: proposal.right.legalName, rationale })} /><AliasAction open={open === rightKey} onToggle={() => { setOpen(open === rightKey ? null : rightKey); setRationale(""); }} sourceName={proposal.right.legalName} alias={proposal.left.legalName} disabled={confirm.isPending} rationale={rationale} onRationale={setRationale} onConfirm={() => confirm.mutate({ sourceId: proposal.right.id, alias: proposal.left.legalName, rationale })} /></div></article>; })}</div>}</section><div className="mt-4 flex gap-2 rounded-xl border border-white/[0.07] bg-white/[0.02] p-4 text-xs leading-5 text-slate-500"><BadgeCheck className="mt-0.5 h-4 w-4 shrink-0 text-emerald-300" />Confirmation preserves both master records. It only adds the selected retained name as a versioned trading alias and writes the Reviewer rationale to the audit trail.</div></div>;
}
function Metric({ icon: Icon, label, value, text, tone }: { icon: typeof Sparkles; label: string; value: string | number; text: string; tone: "blue" | "amber" | "emerald" }) { const toneClasses = { blue: "bg-blue-400/[0.08] text-blue-200", amber: "bg-amber-400/[0.08] text-amber-100", emerald: "bg-emerald-400/[0.08] text-emerald-200" }; return <div className="panel p-5"><div className={`grid h-9 w-9 place-items-center rounded-lg ${toneClasses[tone]}`}><Icon className="h-4 w-4" /></div><p className="mt-4 text-2xl font-semibold tracking-[-0.04em] text-slate-100">{value}</p><p className="mt-1 text-sm font-medium text-slate-300">{label}</p><p className="mt-1 text-xs text-slate-600">{text}</p></div>; }
function Master({ name, country }: { name: string; country: string }) { return <div className="rounded-xl border border-white/[0.08] bg-white/[0.02] p-4"><p className="text-[10px] font-semibold uppercase tracking-[0.13em] text-slate-600">Active counterparty master · {country}</p><p className="mt-2 text-sm font-semibold text-slate-100">{name}</p></div>; }
function AliasAction({ open, onToggle, sourceName, alias, disabled, rationale, onRationale, onConfirm }: { open: boolean; onToggle: () => void; sourceName: string; alias: string; disabled: boolean; rationale: string; onRationale: (value: string) => void; onConfirm: () => void }) { return <div className="rounded-xl border border-white/[0.08] bg-white/[0.02] p-4"><p className="text-xs font-medium text-slate-200">Add <span className="font-semibold text-blue-200">{alias}</span> as an alias of {sourceName}</p><p className="mt-1 text-[11px] leading-4 text-slate-500">Creates a successor version; does not merge the two masters.</p><Button onClick={onToggle} variant="outline" size="sm" className="mt-3 border-blue-400/20 bg-blue-400/[0.03] text-blue-200">{open ? "Cancel" : "Review alias confirmation"}</Button>{open && <div className="mt-3"><Textarea value={rationale} onChange={event => onRationale(event.target.value)} placeholder="Why is this retained name a safe trading alias?" aria-label={`Rationale for alias ${alias}`} className="min-h-20 border-white/[0.1] bg-[#111827] text-xs text-slate-200" /><Button onClick={onConfirm} disabled={disabled || rationale.trim().length < 12} className="mt-3 bg-blue-500 text-white hover:bg-blue-400">Confirm versioned alias</Button></div>}</div>; }
