import { PageTitle } from "@/components/arcway/primitives";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { trpc } from "@/lib/trpc";
import { BarChart3, CircleCheckBig, Clock3, Globe2, Radar, ShieldAlert, UsersRound } from "lucide-react";

type Trade = { id: number; reference: string; sellerName: string; buyerName: string; commodity: string; originCountry: string; destinationCountry: string; totalValue: string | number; assuranceState: string; trustBand: string; executionState: string; documentState: string; resolvedAt: Date | string | null; submittedAt: Date | string | null; createdAt: Date | string };
type Concentration = { label: string; value: number; trades: number; blocked: number; critical: number };
const currency = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
const hoursBetween = (from: Date | string | null, to: Date | string | null) => from && to ? Math.max(0, (new Date(to).getTime() - new Date(from).getTime()) / 3600000) : null;
function group(rows: Trade[], key: (trade: Trade) => string): Concentration[] { const values = new Map<string, Concentration>(); rows.forEach(trade => { const label = key(trade) || "Unclassified"; const entry = values.get(label) ?? { label, value: 0, trades: 0, blocked: 0, critical: 0 }; entry.value += Number(trade.totalValue || 0); entry.trades += 1; entry.blocked += trade.executionState === "blocked" ? 1 : 0; entry.critical += trade.trustBand === "critical" ? 1 : 0; values.set(label, entry); }); return Array.from(values.values()).sort((a, b) => b.value - a.value); }

export default function ExecutiveOutcomes() {
  const trades = trpc.trades.list.useQuery(undefined, { retry: false }); const rows = (trades.data ?? []) as Trade[]; const totalValue = rows.reduce((sum, trade) => sum + Number(trade.totalValue || 0), 0); const completed = rows.filter(trade => trade.assuranceState === "approved" || trade.assuranceState === "rejected"); const approved = rows.filter(trade => trade.assuranceState === "approved"); const cleanFirstPass = approved.filter(trade => trade.trustBand === "ready").length; const preventionSignals = rows.filter(trade => trade.executionState === "blocked" || ["critical", "guarded"].includes(trade.trustBand)).length; const decisionCycles = completed.map(trade => hoursBetween(trade.submittedAt, trade.resolvedAt)).filter((value): value is number => value !== null); const tradeCycles = completed.map(trade => hoursBetween(trade.createdAt, trade.resolvedAt)).filter((value): value is number => value !== null); const averageDecision = decisionCycles.length ? decisionCycles.reduce((sum, value) => sum + value, 0) / decisionCycles.length : 0; const averageTrade = tradeCycles.length ? tradeCycles.reduce((sum, value) => sum + value, 0) / tradeCycles.length : 0; const nativeReady = rows.filter(trade => trade.documentState === "complete").length;
  const counterparties = group(rows, trade => trade.sellerName); const corridors = group(rows, trade => `${trade.originCountry} → ${trade.destinationCountry}`); const commodities = group(rows, trade => trade.commodity); const trustBands = group(rows, trade => trade.trustBand); const trustNetwork = group(rows.flatMap(trade => [{ ...trade, sellerName: `${trade.sellerName} (seller)` }, { ...trade, sellerName: `${trade.buyerName} (buyer)` }]), trade => trade.sellerName);
  return <div className="mx-auto max-w-[1540px] animate-enter"><PageTitle eyebrow="Executive outcomes & risk" title="Measure assurance performance and reveal where portfolio risk is concentrated." description="These operational metrics are calculated from this organization’s Trade Twin data and retained decisions. They support prioritization, not credit, investment, regulatory, or loss forecasting." />
    <div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-5"><Metric icon={CircleCheckBig} label="Clean first-pass trades" value={`${cleanFirstPass}/${approved.length || 0}`} note="Approved with ready evidence band" tone="emerald" /><Metric icon={ShieldAlert} label="Prevented exception signals" value={String(preventionSignals)} note="Blocked or guarded before execution" tone="amber" /><Metric icon={Clock3} label="Average resolution time" value={decisionCycles.length ? `${averageDecision.toFixed(1)}h` : "—"} note="Submission to recorded decision" tone="blue" /><Metric icon={Radar} label="Evidence-native share" value={`${rows.length ? Math.round((nativeReady / rows.length) * 100) : 0}%`} note="Complete evidence state" tone="blue" /><Metric icon={BarChart3} label="Portfolio value assessed" value={currency(totalValue)} note="Trade Twins in scope" tone="slate" /></div>
    <div className="mt-6 grid gap-5 xl:grid-cols-[1.05fr_0.95fr]"><section className="panel overflow-hidden"><div className="border-b border-white/[0.07] px-6 py-4"><p className="text-sm font-semibold text-slate-100">Operating outcomes</p><p className="mt-1 text-xs text-slate-500">How quickly the portfolio reaches an auditable decision, and where assurance stopped execution-risk signals before a release.</p></div><div className="grid gap-px bg-white/[0.06] sm:grid-cols-2"><Outcome label="Average trade cycle" value={tradeCycles.length ? `${averageTrade.toFixed(1)}h` : "—"} detail="Trade creation to recorded approval or rejection" /><Outcome label="Resolution coverage" value={`${completed.length}/${rows.length || 0}`} detail="Trade Twins with a recorded final assurance decision" /><Outcome label="Clean first-pass rate" value={`${approved.length ? Math.round((cleanFirstPass / approved.length) * 100) : 0}%`} detail="Approved trades reaching ready evidence band" /><Outcome label="Evidence-native share" value={`${rows.length ? Math.round((nativeReady / rows.length) * 100) : 0}%`} detail="Trade Twins with complete document evidence" /></div></section><aside className="panel p-6"><div className="flex items-center gap-2"><Globe2 className="h-4 w-4 text-blue-300" /><p className="text-sm font-semibold text-slate-100">Management interpretation</p></div><div className="mt-5 space-y-4 text-sm leading-6 text-slate-400"><p><span className="font-medium text-slate-200">Concentration</span> describes how much assessed trade value depends on a counterparty, corridor, commodity, or assurance band.</p><p><span className="font-medium text-slate-200">Prevention signals</span> identify blocked, guarded, or critical work before execution; they are not realized loss events.</p><p><span className="font-medium text-slate-200">Trust network</span> exposes repeated buyer and seller connections, then annotates their blocked and critical Trade Twin signals.</p></div></aside></div>
    <Tabs defaultValue="counterparties" className="mt-6"><TabsList className="h-auto flex-wrap justify-start gap-1 rounded-xl border border-white/[0.08] bg-[#101722] p-1"><TabsTrigger value="counterparties">Counterparties</TabsTrigger><TabsTrigger value="corridors">Corridors</TabsTrigger><TabsTrigger value="commodities">Commodities</TabsTrigger><TabsTrigger value="trust">Trust bands</TabsTrigger><TabsTrigger value="network">Trust network</TabsTrigger></TabsList><TabsContent value="counterparties" className="mt-5"><ConcentrationTable title="Counterparty concentration" description="Assessed value and active assurance signals by seller counterparty." data={counterparties} total={totalValue} /></TabsContent><TabsContent value="corridors" className="mt-5"><ConcentrationTable title="Corridor concentration" description="Origin-to-destination dependencies and material blocked or critical signals." data={corridors} total={totalValue} /></TabsContent><TabsContent value="commodities" className="mt-5"><ConcentrationTable title="Commodity concentration" description="Trade exposure by commodity category, with evidence-risk indicators." data={commodities} total={totalValue} /></TabsContent><TabsContent value="trust" className="mt-5"><ConcentrationTable title="Trust-band concentration" description="Assessed value grouped by current evidence trust band." data={trustBands} total={totalValue} /></TabsContent><TabsContent value="network" className="mt-5"><ConcentrationTable title="Trust-network dependency" description="Buyer and seller participation across the portfolio. A participant’s blocked or critical count is derived from their associated Trade Twins." data={trustNetwork} total={totalValue * 2} /></TabsContent></Tabs>
  </div>;
}

function ConcentrationTable({ title, description, data, total }: { title: string; description: string; data: Concentration[]; total: number }) { return <section className="panel overflow-hidden"><div className="border-b border-white/[0.07] px-6 py-4"><p className="text-sm font-semibold text-slate-100">{title}</p><p className="mt-1 text-xs text-slate-500">{description}</p></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left"><thead><tr className="border-b border-white/[0.07] text-[10px] uppercase tracking-[0.12em] text-slate-500"><th className="px-6 py-3">Dimension</th><th className="px-6 py-3">Assessed value</th><th className="px-6 py-3">Share</th><th className="px-6 py-3">Trade Twins</th><th className="px-6 py-3">Risk drivers</th></tr></thead><tbody>{data.map(item => { const share = total ? (item.value / total) * 100 : 0; return <tr key={item.label} className="border-b border-white/[0.05] last:border-0"><td className="px-6 py-4 text-sm text-slate-200">{item.label}</td><td className="px-6 py-4 font-mono text-xs text-blue-200">{currency(item.value)}</td><td className="px-6 py-4"><div className="flex items-center gap-3"><div className="h-1.5 w-24 overflow-hidden rounded-full bg-white/[0.06]"><div className="h-full rounded-full bg-blue-400" style={{ width: `${Math.max(2, Math.min(100, share))}%` }} /></div><span className="text-xs text-slate-400">{share.toFixed(1)}%</span></div></td><td className="px-6 py-4 text-sm text-slate-300">{item.trades}</td><td className="px-6 py-4 text-xs text-slate-400">{item.blocked ? `${item.blocked} blocked` : "No blocked"}{item.critical ? ` · ${item.critical} critical` : ""}</td></tr>; })}{!data.length && <tr><td colSpan={5} className="px-6 py-12 text-center text-sm text-slate-500">No Trade Twin data is available for this reporting dimension.</td></tr>}</tbody></table></div></section>; }
function Outcome({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="bg-[#101722] p-6"><p className="text-2xl font-semibold text-slate-100">{value}</p><p className="mt-2 text-sm text-slate-300">{label}</p><p className="mt-1 text-xs leading-5 text-slate-500">{detail}</p></div>; }
function Metric({ icon: Icon, label, value, note, tone }: { icon: typeof CircleCheckBig; label: string; value: string; note: string; tone: "emerald" | "amber" | "blue" | "slate" }) { const tones = { emerald: "text-emerald-300 bg-emerald-400/[0.08]", amber: "text-amber-300 bg-amber-400/[0.08]", blue: "text-blue-300 bg-blue-400/[0.08]", slate: "text-slate-300 bg-white/[0.06]" }; return <div className="panel p-5"><div className={`grid h-8 w-8 place-items-center rounded-lg ${tones[tone]}`}><Icon className="h-4 w-4" /></div><p className="mt-5 text-2xl font-semibold tracking-tight text-slate-100">{value}</p><p className="mt-1 text-sm text-slate-300">{label}</p><p className="mt-2 text-xs leading-5 text-slate-500">{note}</p></div>; }
