import { useAuth } from "@/_core/hooks/useAuth";
import { EmptyPanel, PageTitle } from "@/components/arcway/primitives";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Braces, FileUp, MailPlus, ShieldAlert } from "lucide-react";
import { ChangeEvent, FormEvent, useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";

type IntakeMode = "email" | "file" | "webhook";

export default function Ingestion() {
  const { user } = useAuth();
  const trades = trpc.trades.list.useQuery(undefined, { retry: false }); const mappings = trpc.operations.integrations.mappings.useQuery(undefined, { retry: false });
  const utils = trpc.useUtils();
  const [tradeId, setTradeId] = useState("");
  const [mode, setMode] = useState<IntakeMode>(user?.role === "reviewer" ? "webhook" : "email");
  const [sender, setSender] = useState(""); const [subject, setSubject] = useState(""); const [body, setBody] = useState("");
  const [fileName, setFileName] = useState(""); const [fileMimeType, setFileMimeType] = useState(""); const [fileBase64, setFileBase64] = useState(""); const [mappingId, setMappingId] = useState(""); const [structuredPayload, setStructuredPayload] = useState('{\n  "reference": "",\n  "source": ""\n}'); const [simulateFailure, setSimulateFailure] = useState(false);
  const ingestEmail = trpc.trades.ingestion.email.useMutation({ onSuccess: () => { toast.success("Email source ingested into the Trade Twin"); setSender(""); setSubject(""); setBody(""); utils.trades.get.invalidate(); utils.trades.dashboard.invalidate(); }, onError: error => toast.error(error.message) });
  const ingestSource = trpc.operations.integrations.ingestSource.useMutation({ onSuccess: result => { toast.success(`Source receipt ${result.receiptId} ${result.status}; provenance retained for replay and review.`); setFileName(""); setFileMimeType(""); setFileBase64(""); setSimulateFailure(false); utils.operations.integrations.list.invalidate(); utils.trades.get.invalidate(); }, onError: error => toast.error(error.message) });
  const submitEmail = (event: FormEvent) => { event.preventDefault(); if (!tradeId) return toast.error("Choose a Trade Twin first."); ingestEmail.mutate({ tradeId: Number(tradeId), sender, subject, body }); };
  const readFile = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 10_000_000) return toast.error("Files must be 10 MB or smaller."); const reader = new FileReader(); reader.onload = () => { setFileName(file.name); setFileMimeType(file.type || "text/plain"); setFileBase64(String(reader.result).split(",")[1] || ""); }; reader.readAsDataURL(file); };
  const submitFile = () => { if (!tradeId) return toast.error("Choose a Trade Twin first."); let payload: Record<string, unknown> | undefined; try { payload = structuredPayload.trim() ? JSON.parse(structuredPayload) : undefined; } catch { return toast.error("Structured metadata must be valid JSON."); } ingestSource.mutate({ tradeId: Number(tradeId), mappingId: mappingId ? Number(mappingId) : undefined, sourceType: fileMimeType === "text/csv" || fileMimeType.includes("spreadsheet") || fileMimeType === "application/json" ? "structured_file" : "email_attachment", fileName: fileName || undefined, mimeType: fileMimeType as any || undefined, base64: fileBase64 || undefined, payload, simulateFailure }); };
  const submitWebhook = () => { if (!tradeId) return toast.error("Choose a Trade Twin first."); try { ingestSource.mutate({ tradeId: Number(tradeId), sourceType: "webhook", payload: JSON.parse(structuredPayload), simulateFailure }); } catch { toast.error("Webhook payload must be valid JSON."); } };

  if (!trades.data?.length) return <div className="mx-auto max-w-4xl"><PageTitle eyebrow="Source intake" title="Ingest source material with retained provenance." description="ARCWAY needs a canonical Trade Twin before it can attach correspondence, source files, or normalized webhook evidence." /><EmptyPanel title="Create a Trade Twin before ingesting source material" description="Source receipts are scoped to a Trade Twin and retain their operational lineage." action={<Link href="/trades/new"><Button className="bg-blue-500 text-white hover:bg-blue-400">Create trade</Button></Link>} /></div>;

  const traderMode = user?.role === "trader";
  return <div className="mx-auto max-w-4xl animate-enter"><PageTitle eyebrow="Source intake" title="Turn correspondence and source data into traceable trade state." description="Every intake stores its immutable source receipt, normalized outcome, hash, link to the Trade Twin, and operator recovery state. Source data never silently overwrites canonical trade facts." />
    <div className="mt-6 panel overflow-hidden"><div className="border-b border-white/[0.07] px-6 pt-5"><div className="flex flex-wrap gap-2">{traderMode && <ModeButton active={mode === "email"} onClick={() => setMode("email")} icon={MailPlus} label="Email correspondence" />}{traderMode && <ModeButton active={mode === "file"} onClick={() => setMode("file")} icon={FileUp} label="Attachments & files" />}<ModeButton active={mode === "webhook"} onClick={() => setMode("webhook")} icon={Braces} label="Webhook receipt" /></div></div>
      <div className="space-y-5 p-6 md:p-8"><div><Label className="text-xs font-medium text-slate-400">Trade Twin</Label><select value={tradeId} onChange={event => setTradeId(event.target.value)} className="mt-2 h-11 w-full rounded-lg border border-white/[0.1] bg-[#111827] px-3 text-sm text-slate-200 outline-none"><option value="">Select a Trade Twin</option>{trades.data.map(trade => <option key={trade.id} value={trade.id}>{trade.reference} — {trade.sellerName} → {trade.buyerName}</option>)}</select></div>
        {mode === "email" && <form onSubmit={submitEmail} className="space-y-5"><div className="grid gap-5 md:grid-cols-2"><div><Label className="text-xs font-medium text-slate-400">Sender</Label><Input value={sender} onChange={event => setSender(event.target.value)} type="email" placeholder="operations@counterparty.com" className="mt-2 h-11 border-white/[0.1] bg-[#111827] text-slate-200 placeholder:text-slate-600" /></div><div><Label className="text-xs font-medium text-slate-400">Subject</Label><Input value={subject} onChange={event => setSubject(event.target.value)} placeholder="RE: Cargo ready date amendment" className="mt-2 h-11 border-white/[0.1] bg-[#111827] text-slate-200 placeholder:text-slate-600" /></div></div><div><Label className="text-xs font-medium text-slate-400">Email body</Label><Textarea value={body} onChange={event => setBody(event.target.value)} placeholder="Paste the source correspondence exactly as received…" className="mt-2 min-h-52 border-white/[0.1] bg-[#111827] text-sm leading-6 text-slate-200 placeholder:text-slate-600" /></div><div className="flex justify-end"><Button disabled={ingestEmail.isPending || !tradeId || !sender || subject.trim().length < 3 || body.trim().length < 4} className="bg-blue-500 text-white hover:bg-blue-400"><MailPlus className="mr-2 h-4 w-4" />{ingestEmail.isPending ? "Ingesting source…" : "Ingest email source"}</Button></div></form>}
        {mode === "file" && <div className="space-y-5"><div className="rounded-xl border border-dashed border-white/[0.15] bg-white/[0.02] p-5"><Label className="text-xs font-medium text-slate-300">Attachment or structured file</Label><Input type="file" accept=".pdf,.jpg,.jpeg,.png,.txt,.csv,.json,.xlsx" onChange={readFile} className="mt-3 border-white/[0.1] bg-[#111827] text-slate-200 file:mr-4 file:border-0 file:bg-blue-500 file:px-3 file:py-1.5 file:text-xs file:text-white" />{fileName && <p className="mt-3 text-xs text-blue-200">{fileName} · {fileMimeType || "detected source type"} · securely staged for ingestion</p>}</div>{(fileMimeType === "text/csv" || fileMimeType.includes("spreadsheet") || fileMimeType === "application/json") && <div className="rounded-xl border border-blue-400/15 bg-blue-400/[0.035] p-5"><Label className="text-xs font-medium text-blue-100">Reusable field mapping</Label><select value={mappingId} onChange={event => setMappingId(event.target.value)} className="mt-2 h-10 w-full rounded-lg border border-white/[0.1] bg-[#111827] px-3 text-xs text-slate-200"><option value="">Retain parsed rows without a mapping</option>{mappings.data?.map(mapping => <option key={mapping.id} value={mapping.id}>{mapping.sourceName} · {mapping.entityType} mapping</option>)}</select><p className="mt-3 text-xs leading-5 text-blue-100/70">ARCWAY applies the selected mapping only to the retained source preview. A reviewer must separately select source evidence in Canonicalization before any Trade Twin fact is adopted.</p></div>}<div><Label className="text-xs font-medium text-slate-400">Structured metadata or parsed row preview</Label><Textarea value={structuredPayload} onChange={event => setStructuredPayload(event.target.value)} className="mt-2 min-h-36 border-white/[0.1] bg-[#111827] font-mono text-xs text-slate-200" /></div><label className="flex items-center gap-2 rounded-lg border border-amber-400/15 bg-amber-400/[0.04] px-4 py-3 text-xs text-amber-100"><input type="checkbox" checked={simulateFailure} onChange={event => setSimulateFailure(event.target.checked)} />Test recovery queue by recording a failed normalization</label><div className="flex justify-end"><Button disabled={ingestSource.isPending || !tradeId || (!fileBase64 && !structuredPayload.trim())} onClick={submitFile} className="bg-blue-500 text-white hover:bg-blue-400"><FileUp className="mr-2 h-4 w-4" />{ingestSource.isPending ? "Normalizing…" : "Normalize source file"}</Button></div></div>}
        {mode === "webhook" && <div className="space-y-5"><div className="rounded-lg border border-amber-400/15 bg-amber-400/[0.04] px-4 py-3 text-xs leading-5 text-amber-100">Webhook normalization is reviewer-controlled in this workspace. The receipt payload is retained separately from canonical trade facts and can be replayed from operational monitoring.</div><div><Label className="text-xs font-medium text-slate-400">Normalized provider payload</Label><Textarea value={structuredPayload} onChange={event => setStructuredPayload(event.target.value)} className="mt-2 min-h-52 border-white/[0.1] bg-[#111827] font-mono text-xs text-slate-200" /></div><label className="flex items-center gap-2 rounded-lg border border-amber-400/15 bg-amber-400/[0.04] px-4 py-3 text-xs text-amber-100"><input type="checkbox" checked={simulateFailure} onChange={event => setSimulateFailure(event.target.checked)} />Record as failed to test alerting and replay controls</label><div className="flex justify-end"><Button disabled={user?.role !== "reviewer" || ingestSource.isPending || !tradeId} onClick={submitWebhook} className="bg-blue-500 text-white hover:bg-blue-400"><Braces className="mr-2 h-4 w-4" />{ingestSource.isPending ? "Normalizing…" : "Retain webhook receipt"}</Button></div></div>}
      </div>
    </div>
  </div>;
}

function ModeButton({ active, onClick, icon: Icon, label }: { active: boolean; onClick: () => void; icon: typeof MailPlus; label: string }) { return <button onClick={onClick} className={`flex items-center gap-2 border-b-2 px-3 py-3 text-xs font-medium transition-colors ${active ? "border-blue-400 text-blue-200" : "border-transparent text-slate-500 hover:text-slate-300"}`}><Icon className="h-3.5 w-3.5" />{label}</button>; }
