import { useAuth } from "@/_core/hooks/useAuth";
import { PageTitle } from "@/components/arcway/primitives";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, ArrowRight, Check, ShieldAlert } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { useLocation } from "wouter";
import { toast } from "sonner";

const STEPS = ["Parties", "Goods & value", "Delivery", "Confirm"];
const initial = { buyerName: "", buyerCountry: "", sellerName: "", sellerCountry: "", commodity: "", quantity: "", unit: "MT", unitPrice: "", totalValue: "", currency: "USD", incoterm: "FOB", originCountry: "", destinationCountry: "", expectedShipmentDate: "" };

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><Label className="mb-2 block text-xs font-medium text-slate-400">{label}</Label>{children}</label>; }
function TextInput({ value, onChange, placeholder, type = "text" }: { value: string; onChange: (value: string) => void; placeholder: string; type?: string }) { return <Input type={type} value={value} onChange={event => onChange(event.target.value)} placeholder={placeholder} className="h-11 border-white/[0.1] bg-white/[0.035] text-slate-100 placeholder:text-slate-600 focus-visible:border-blue-400/60 focus-visible:ring-blue-400/20" />; }

export default function NewTrade() {
  const { user } = useAuth(); const [, navigate] = useLocation(); const [step, setStep] = useState(0); const [form, setForm] = useState(initial); const create = trpc.trades.create.useMutation({ onSuccess: data => { toast.success("Trade Twin created"); navigate(`/trades/${data.tradeId}`); }, onError: error => toast.error(error.message) });
  const calculatedValue = useMemo(() => Number(form.quantity || 0) * Number(form.unitPrice || 0), [form.quantity, form.unitPrice]);
  const set = (key: keyof typeof initial) => (value: string) => setForm(previous => ({ ...previous, [key]: value }));
  const validateStep = () => { const requirements = step === 0 ? [form.buyerName, form.buyerCountry, form.sellerName, form.sellerCountry] : step === 1 ? [form.commodity, form.quantity, form.unit, form.unitPrice] : step === 2 ? [form.incoterm, form.originCountry, form.destinationCountry, form.expectedShipmentDate] : []; return requirements.every(Boolean); };
  const next = () => { if (!validateStep()) return toast.error("Complete the required fields before continuing."); if (step === 1 && !form.totalValue) setForm(previous => ({ ...previous, totalValue: calculatedValue.toFixed(2) })); setStep(value => Math.min(3, value + 1)); };
  const submit = (event: FormEvent) => { event.preventDefault(); if (user?.role !== "trader") return toast.error("Only Traders can create a trade."); create.mutate({ ...form, totalValue: form.totalValue || calculatedValue.toFixed(2), buyerCountry: form.buyerCountry.toUpperCase(), sellerCountry: form.sellerCountry.toUpperCase(), originCountry: form.originCountry.toUpperCase(), destinationCountry: form.destinationCountry.toUpperCase(), currency: form.currency.toUpperCase(), expectedShipmentDate: new Date(form.expectedShipmentDate) }); };
  if (user?.role === "reviewer") return <div className="mx-auto max-w-xl"><PageTitle eyebrow="Restricted action" title="Trade creation is gated to Traders." description="Reviewers protect the assurance workflow by reviewing submitted Trade Twins rather than creating them." /><div className="panel p-6"><ShieldAlert className="h-6 w-6 text-amber-300" /><p className="mt-3 text-sm text-slate-400">Switch to a Trader workspace to submit a new trade for assurance.</p><Button onClick={() => navigate("/review")} className="mt-5 bg-blue-500 text-white hover:bg-blue-400">Open review queue</Button></div></div>;
  return <div className="mx-auto max-w-4xl animate-enter"><PageTitle eyebrow="New Trade Twin" title="Capture the commercial truth first." description="ARCWAY creates a canonical, evidence-ready representation of the transaction. Required documents will be prepared after creation." />
    <div className="mb-7 grid grid-cols-4 gap-1 rounded-xl border border-white/[0.08] bg-white/[0.025] p-1">{STEPS.map((name, index) => <div key={name} className={`flex items-center gap-2 rounded-lg px-3 py-2.5 ${index === step ? "bg-blue-400/[0.11] text-blue-200" : index < step ? "text-emerald-300" : "text-slate-600"}`}><span className={`grid h-5 w-5 place-items-center rounded-full text-[10px] font-bold ${index < step ? "bg-emerald-400/20" : index === step ? "bg-blue-400/20" : "bg-white/[0.05]"}`}>{index < step ? <Check className="h-3 w-3" /> : index + 1}</span><span className="hidden text-xs font-medium sm:block">{name}</span></div>)}</div>
    <form onSubmit={submit} className="panel overflow-hidden"><div className="min-h-[360px] p-6 md:p-8">{step === 0 && <div><p className="eyebrow">01 — Commercial parties</p><h2 className="mt-2 text-xl font-semibold text-slate-100">Who is trading with whom?</h2><p className="mt-2 text-sm text-slate-500">Name the contracting parties and their country of incorporation.</p><div className="mt-7 grid gap-5 md:grid-cols-2"><div className="rounded-xl border border-white/[0.08] bg-white/[0.025] p-5"><p className="mb-5 text-xs font-semibold uppercase tracking-[0.14em] text-blue-300">Seller / exporter</p><div className="space-y-4"><Field label="Legal entity name"><TextInput value={form.sellerName} onChange={set("sellerName")} placeholder="e.g. Meridian Commodities Ltd." /></Field><Field label="Country (ISO code)"><TextInput value={form.sellerCountry} onChange={set("sellerCountry")} placeholder="e.g. AE" /></Field></div></div><div className="rounded-xl border border-white/[0.08] bg-white/[0.025] p-5"><p className="mb-5 text-xs font-semibold uppercase tracking-[0.14em] text-violet-300">Buyer / importer</p><div className="space-y-4"><Field label="Legal entity name"><TextInput value={form.buyerName} onChange={set("buyerName")} placeholder="e.g. Northstar Foods GmbH" /></Field><Field label="Country (ISO code)"><TextInput value={form.buyerCountry} onChange={set("buyerCountry")} placeholder="e.g. DE" /></Field></div></div></div></div>}
      {step === 1 && <div><p className="eyebrow">02 — Goods & value</p><h2 className="mt-2 text-xl font-semibold text-slate-100">Define the agreed commercial terms.</h2><div className="mt-7 grid gap-5 md:grid-cols-2"><Field label="Commodity / goods"><TextInput value={form.commodity} onChange={set("commodity")} placeholder="e.g. Arabica coffee beans, grade 1" /></Field><Field label="Currency"><TextInput value={form.currency} onChange={set("currency")} placeholder="USD" /></Field><Field label="Quantity"><TextInput value={form.quantity} onChange={set("quantity")} placeholder="e.g. 24000" type="number" /></Field><Field label="Unit"><TextInput value={form.unit} onChange={set("unit")} placeholder="e.g. MT" /></Field><Field label="Unit price"><TextInput value={form.unitPrice} onChange={set("unitPrice")} placeholder="e.g. 425.50" type="number" /></Field><Field label="Total value"><TextInput value={form.totalValue} onChange={set("totalValue")} placeholder={calculatedValue ? calculatedValue.toFixed(2) : "Calculated from quantity × unit price"} type="number" /></Field></div><div className="mt-6 rounded-xl border border-blue-400/15 bg-blue-400/[0.06] px-5 py-4"><p className="text-xs text-blue-200">Calculated contract value <span className="ml-2 text-lg font-semibold">{form.currency || "USD"} {calculatedValue.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span></p></div></div>}
      {step === 2 && <div><p className="eyebrow">03 — Delivery</p><h2 className="mt-2 text-xl font-semibold text-slate-100">Set the physical handoff expectations.</h2><div className="mt-7 grid gap-5 md:grid-cols-2"><Field label="Incoterm"><TextInput value={form.incoterm} onChange={set("incoterm")} placeholder="e.g. FOB" /></Field><Field label="Expected shipment date"><TextInput value={form.expectedShipmentDate} onChange={set("expectedShipmentDate")} placeholder="" type="date" /></Field><Field label="Country of origin (ISO code)"><TextInput value={form.originCountry} onChange={set("originCountry")} placeholder="e.g. BR" /></Field><Field label="Destination country (ISO code)"><TextInput value={form.destinationCountry} onChange={set("destinationCountry")} placeholder="e.g. DE" /></Field></div></div>}
      {step === 3 && <div><p className="eyebrow">04 — Confirm Trade Twin</p><h2 className="mt-2 text-xl font-semibold text-slate-100">Review the canonical transaction.</h2><p className="mt-2 text-sm text-slate-500">On creation, ARCWAY prepares six required evidence slots and begins an immutable activity ledger.</p><div className="mt-7 grid gap-px overflow-hidden rounded-xl border border-white/[0.08] bg-white/[0.08] sm:grid-cols-2">{[["Seller", form.sellerName], ["Buyer", form.buyerName], ["Commodity", form.commodity], ["Total value", `${form.currency} ${form.totalValue || calculatedValue.toFixed(2)}`], ["Route", `${form.originCountry} → ${form.destinationCountry}`], ["Incoterm", form.incoterm], ["Shipment", form.expectedShipmentDate], ["Required evidence", "6 documents"]].map(([label, value]) => <div key={label} className="bg-[#111827] px-5 py-4"><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-slate-500">{label}</p><p className="mt-1 text-sm font-medium text-slate-200">{value || "—"}</p></div>)}</div></div>}</div>
      <div className="flex items-center justify-between border-t border-white/[0.07] bg-white/[0.015] px-6 py-4 md:px-8"><Button type="button" variant="ghost" disabled={step === 0} onClick={() => setStep(value => value - 1)} className="text-slate-400 hover:bg-white/[0.05] hover:text-slate-100"><ArrowLeft className="mr-2 h-4 w-4" />Back</Button>{step < 3 ? <Button type="button" onClick={next} className="bg-blue-500 text-white hover:bg-blue-400">Continue<ArrowRight className="ml-2 h-4 w-4" /></Button> : <Button type="submit" disabled={create.isPending} className="bg-blue-500 text-white hover:bg-blue-400">{create.isPending ? "Creating…" : "Create Trade Twin"}<Check className="ml-2 h-4 w-4" /></Button>}</div>
    </form></div>;
}

