import { useAuth } from "@/_core/hooks/useAuth";
import { PageTitle } from "@/components/arcway/primitives";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { trpc } from "@/lib/trpc";
import { Boxes, ClipboardCheck, Landmark, PackageSearch, ShipWheel, Split } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function OperationsHub() {
  const { user } = useAuth();
  const masters = trpc.operations.masters.list.useQuery(undefined, { retry: false });
  const trades = trpc.trades.list.useQuery(undefined, { retry: false });
  const utils = trpc.useUtils();
  const [counterparty, setCounterparty] = useState(""); const [country, setCountry] = useState(""); const [sku, setSku] = useState(""); const [description, setDescription] = useState(""); const [policyName, setPolicyName] = useState(""); const [tradeId, setTradeId] = useState(""); const [booking, setBooking] = useState(""); const [terms, setTerms] = useState("letter_of_credit");
  const [counterpartySource, setCounterpartySource] = useState(""); const [counterpartySuccessorName, setCounterpartySuccessorName] = useState(""); const [productSource, setProductSource] = useState(""); const [productSuccessorDescription, setProductSuccessorDescription] = useState("");
  const [bindingPolicy, setBindingPolicy] = useState(""); const [bindingTemplate, setBindingTemplate] = useState(""); const [bindingCounterparty, setBindingCounterparty] = useState(""); const [bindingProduct, setBindingProduct] = useState(""); const [bindingRole, setBindingRole] = useState<"buyer" | "supplier" | "any">("buyer");
  const templates = trpc.operations.obligations.listTemplates.useQuery(undefined, { retry: false });
  const createCounterparty = trpc.operations.masters.createCounterparty.useMutation({ onSuccess: () => { toast.success("Counterparty profile created"); setCounterparty(""); setCountry(""); utils.operations.masters.list.invalidate(); }, onError: e => toast.error(e.message) });
  const createProduct = trpc.operations.masters.createProduct.useMutation({ onSuccess: () => { toast.success("Product master v1 created"); setSku(""); setDescription(""); utils.operations.masters.list.invalidate(); }, onError: e => toast.error(e.message) });
  const createCounterpartyVersion = trpc.operations.masters.createCounterpartyVersion.useMutation({ onSuccess: () => { toast.success("Immutable counterparty successor created"); setCounterpartySource(""); setCounterpartySuccessorName(""); utils.operations.masters.list.invalidate(); }, onError: e => toast.error(e.message) });
  const createProductVersion = trpc.operations.masters.createProductVersion.useMutation({ onSuccess: () => { toast.success("Immutable product successor created"); setProductSource(""); setProductSuccessorDescription(""); utils.operations.masters.list.invalidate(); }, onError: e => toast.error(e.message) });
  const createPolicy = trpc.operations.policies.create.useMutation({ onSuccess: () => { toast.success("Active policy pack created"); setPolicyName(""); utils.operations.masters.list.invalidate(); }, onError: e => toast.error(e.message) });
  const bindPolicy = trpc.operations.policies.bindObligation.useMutation({ onSuccess: () => { toast.success("Relationship policy binding created"); setBindingPolicy(""); setBindingTemplate(""); setBindingCounterparty(""); setBindingProduct(""); utils.operations.masters.list.invalidate(); }, onError: e => toast.error(e.message) });
  const createShipment = trpc.operations.shipments.create.useMutation({ onSuccess: () => { toast.success("Shipment allocation created"); setBooking(""); utils.trades.get.invalidate(); }, onError: e => toast.error(e.message) });
  const updateTerms = trpc.operations.settlement.upsertTerms.useMutation({ onSuccess: () => { toast.success("Settlement terms recorded"); utils.trades.get.invalidate(); }, onError: e => toast.error(e.message) });
  const canTrade = user?.role === "trader"; const isReviewer = user?.role === "reviewer";
  const activeCounterparties = masters.data?.counterparties.filter(item => !item.validTo) ?? [];
  const activeProducts = masters.data?.products.filter(item => !item.validTo) ?? [];

  return <div className="mx-auto max-w-[1540px] animate-enter">
    <PageTitle eyebrow="Operations control" title="Reusable commercial rules, execution, and settlement." description="Manage shared master records and governed policies so every Trade Twin can be reconstructed from retained, versioned operating facts." />
    <Tabs defaultValue="masters" className="mt-6"><TabsList className="h-auto flex-wrap justify-start gap-1 rounded-xl border border-white/[0.08] bg-[#101722] p-1"><TabsTrigger value="masters">Masters</TabsTrigger><TabsTrigger value="policy">Policy packs</TabsTrigger><TabsTrigger value="shipment">Shipment</TabsTrigger><TabsTrigger value="settlement">Settlement</TabsTrigger></TabsList>
      <TabsContent value="masters" className="mt-5 grid gap-5 xl:grid-cols-2">
        <div className="panel p-6"><div className="flex items-center gap-2"><Boxes className="h-4 w-4 text-blue-300" /><p className="text-sm font-semibold text-slate-100">Counterparty master</p></div><p className="mt-2 text-xs leading-5 text-slate-500">Legal entities retain their version lineage. A successor ends the prior effective period; it never overwrites trading facts already used by a Trade Twin.</p><div className="mt-5 grid gap-3 md:grid-cols-2"><Input value={counterparty} onChange={e => setCounterparty(e.target.value)} placeholder="Legal entity name" className="border-white/[0.1] bg-[#111827] text-slate-200" /><Input value={country} onChange={e => setCountry(e.target.value.toUpperCase())} placeholder="Country (e.g. DE)" maxLength={2} className="border-white/[0.1] bg-[#111827] text-slate-200" /></div><Button disabled={!canTrade || !counterparty || country.length !== 2 || createCounterparty.isPending} onClick={() => createCounterparty.mutate({ legalName: counterparty, countryCode: country })} className="mt-3 bg-blue-500 text-white hover:bg-blue-400">Create counterparty</Button>
          {isReviewer && <div className="mt-5 rounded-xl border border-blue-400/15 bg-blue-400/[0.035] p-4"><p className="text-xs font-semibold text-blue-100">Create governed successor</p><div className="mt-3 grid gap-2"><select value={counterpartySource} onChange={event => setCounterpartySource(event.target.value)} className="h-10 rounded-md border border-white/[0.1] bg-[#111827] px-3 text-xs text-slate-200"><option value="">Choose active counterparty</option>{activeCounterparties.map(item => <option key={item.id} value={item.id}>{item.legalName} · v{item.version}</option>)}</select><Input value={counterpartySuccessorName} onChange={event => setCounterpartySuccessorName(event.target.value)} placeholder="Revised legal entity name (optional)" className="border-white/[0.1] bg-[#111827] text-slate-200" /></div><Button disabled={!counterpartySource || createCounterpartyVersion.isPending} onClick={() => createCounterpartyVersion.mutate({ sourceId: Number(counterpartySource), legalName: counterpartySuccessorName || undefined })} variant="outline" className="mt-3 border-blue-400/25 text-blue-100 hover:bg-blue-400/[0.08]"><Split className="mr-1.5 h-4 w-4" />Create vNext</Button></div>}
          <div className="mt-6 space-y-2 border-t border-white/[0.07] pt-5">{masters.data?.counterparties.map(item => <div key={item.id} className="rounded-lg border border-white/[0.07] px-3 py-3"><p className="text-sm text-slate-200">{item.legalName} <span className="font-mono text-xs text-blue-300">v{item.version}</span></p><p className="mt-1 text-xs text-slate-500">{item.countryCode} · {item.validTo ? `superseded ${new Date(item.validTo).toLocaleDateString()}` : item.status}</p></div>)}</div>
        </div>
        <div className="panel p-6"><div className="flex items-center gap-2"><PackageSearch className="h-4 w-4 text-blue-300" /><p className="text-sm font-semibold text-slate-100">Product master</p></div><p className="mt-2 text-xs leading-5 text-slate-500">Reusable classifications, packing, lead-time, origin, and compliance attributes retain a product-specific version lineage.</p><div className="mt-5 grid gap-3"><Input value={sku} onChange={e => setSku(e.target.value)} placeholder="SKU" className="border-white/[0.1] bg-[#111827] text-slate-200" /><Textarea value={description} onChange={e => setDescription(e.target.value)} placeholder="Product description" className="min-h-24 border-white/[0.1] bg-[#111827] text-slate-200" /></div><Button disabled={!canTrade || !sku || !description || createProduct.isPending} onClick={() => createProduct.mutate({ sku, description })} className="mt-3 bg-blue-500 text-white hover:bg-blue-400">Create product</Button>
          {isReviewer && <div className="mt-5 rounded-xl border border-blue-400/15 bg-blue-400/[0.035] p-4"><p className="text-xs font-semibold text-blue-100">Create governed successor</p><div className="mt-3 grid gap-2"><select value={productSource} onChange={event => setProductSource(event.target.value)} className="h-10 rounded-md border border-white/[0.1] bg-[#111827] px-3 text-xs text-slate-200"><option value="">Choose active product</option>{activeProducts.map(item => <option key={item.id} value={item.id}>{item.sku} · v{item.version}</option>)}</select><Textarea value={productSuccessorDescription} onChange={event => setProductSuccessorDescription(event.target.value)} placeholder="Revised description (optional)" className="min-h-16 border-white/[0.1] bg-[#111827] text-slate-200" /></div><Button disabled={!productSource || createProductVersion.isPending} onClick={() => createProductVersion.mutate({ sourceId: Number(productSource), description: productSuccessorDescription || undefined })} variant="outline" className="mt-3 border-blue-400/25 text-blue-100 hover:bg-blue-400/[0.08]"><Split className="mr-1.5 h-4 w-4" />Create vNext</Button></div>}
          <div className="mt-6 space-y-2 border-t border-white/[0.07] pt-5">{masters.data?.products.map(item => <div key={item.id} className="rounded-lg border border-white/[0.07] px-3 py-3"><p className="text-sm text-slate-200">{item.sku} · <span className="font-mono text-xs text-blue-300">v{item.version}</span></p><p className="mt-1 text-xs text-slate-500">{item.description}{item.validTo ? ` · superseded ${new Date(item.validTo).toLocaleDateString()}` : ""}</p></div>)}</div>
        </div>
      </TabsContent>
      <TabsContent value="policy" className="mt-5 grid gap-5 xl:grid-cols-[0.9fr_1.1fr]"><div className="space-y-5"><div className="panel p-6"><div className="flex items-center gap-2"><ClipboardCheck className="h-4 w-4 text-blue-300" /><p className="text-sm font-semibold text-slate-100">Policy pack authoring</p></div><p className="mt-2 text-xs leading-5 text-slate-500">Policy packs create deterministic evidence and release controls. They are not legal, regulatory, banking, or compliance certification.</p><Input value={policyName} onChange={e => setPolicyName(e.target.value)} placeholder="e.g. Documentary presentation policy" className="mt-5 border-white/[0.1] bg-[#111827] text-slate-200" /><Button disabled={!isReviewer || !policyName || createPolicy.isPending} onClick={() => createPolicy.mutate({ name: policyName, scope: "payment", rules: [{ if: { payment_method: "letter_of_credit" }, then: { require: "documentary_presentation_pack" } }] })} className="mt-3 bg-blue-500 text-white hover:bg-blue-400">Activate policy pack</Button></div>
        {isReviewer && <div className="panel p-6"><div className="flex items-center gap-2"><Split className="h-4 w-4 text-blue-300" /><p className="text-sm font-semibold text-slate-100">Relationship policy binding</p></div><p className="mt-2 text-xs leading-5 text-slate-500">Bind an active policy to an approved template and optional Buyer/Supplier or product master. The binding is evaluated against retained Trade Twin facts before any obligation is created.</p><div className="mt-4 grid gap-2"><select value={bindingPolicy} onChange={event => setBindingPolicy(event.target.value)} className="h-10 rounded-md border border-white/[0.1] bg-[#111827] px-3 text-xs text-slate-200"><option value="">Active policy pack</option>{masters.data?.policyPacks.filter(item => item.status === "active").map(item => <option key={item.id} value={item.id}>{item.name} · {item.scope}</option>)}</select><select value={bindingTemplate} onChange={event => setBindingTemplate(event.target.value)} className="h-10 rounded-md border border-white/[0.1] bg-[#111827] px-3 text-xs text-slate-200"><option value="">Reusable obligation template</option>{templates.data?.filter(item => item.active === 1).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><div className="grid gap-2 sm:grid-cols-2"><select value={bindingCounterparty} onChange={event => setBindingCounterparty(event.target.value)} className="h-10 rounded-md border border-white/[0.1] bg-[#111827] px-3 text-xs text-slate-200"><option value="">Any counterparty</option>{activeCounterparties.map(item => <option key={item.id} value={item.id}>{item.legalName}</option>)}</select><select value={bindingRole} onChange={event => setBindingRole(event.target.value as "buyer" | "supplier" | "any")} className="h-10 rounded-md border border-white/[0.1] bg-[#111827] px-3 text-xs text-slate-200"><option value="buyer">Buyer relationship</option><option value="supplier">Supplier relationship</option><option value="any">Either counterparty</option></select></div><select value={bindingProduct} onChange={event => setBindingProduct(event.target.value)} className="h-10 rounded-md border border-white/[0.1] bg-[#111827] px-3 text-xs text-slate-200"><option value="">Any product</option>{activeProducts.map(item => <option key={item.id} value={item.id}>{item.sku} · v{item.version}</option>)}</select></div><Button disabled={!bindingPolicy || !bindingTemplate || bindPolicy.isPending} onClick={() => bindPolicy.mutate({ policyPackId: Number(bindingPolicy), obligationTemplateId: Number(bindingTemplate), counterpartyId: bindingCounterparty ? Number(bindingCounterparty) : undefined, productId: bindingProduct ? Number(bindingProduct) : undefined, relationshipRole: bindingRole })} className="mt-3 bg-blue-500 text-white hover:bg-blue-400">Bind policy to template</Button></div>}</div>
        <div className="panel p-6"><p className="text-sm font-semibold text-slate-100">Active policy packs and bindings</p><div className="mt-4 space-y-3">{masters.data?.policyPacks.length ? masters.data.policyPacks.map(policy => <div key={policy.id} className="rounded-lg border border-white/[0.07] bg-white/[0.025] p-4"><p className="text-sm text-slate-200">{policy.name}</p><p className="mt-1 text-xs text-slate-500">{policy.scope} · {policy.status}</p>{masters.data.policyBindings.filter(binding => binding.policyPackId === policy.id).map(binding => <p key={binding.id} className="mt-2 border-l border-blue-400/35 pl-2 text-[11px] text-blue-100">Template #{binding.obligationTemplateId} · {binding.relationshipRole}{binding.counterpartyId ? ` · counterparty #${binding.counterpartyId}` : ""}{binding.productId ? ` · product #${binding.productId}` : ""}</p>)}</div>) : <p className="text-sm text-slate-500">No policy packs configured.</p>}</div></div></TabsContent>
      <TabsContent value="shipment" className="mt-5"><div className="panel max-w-3xl p-6"><div className="flex items-center gap-2"><ShipWheel className="h-4 w-4 text-blue-300" /><p className="text-sm font-semibold text-slate-100">Shipment and allocation</p></div><p className="mt-2 text-xs leading-5 text-slate-500">A shipment can allocate against one or more Trade Twins. Track the booking, route, vessel, cut-offs, and subsequent carrier events without assuming one PO equals one container.</p><div className="mt-5 grid gap-3 md:grid-cols-2"><select value={tradeId} onChange={e => setTradeId(e.target.value)} className="h-10 rounded-md border border-white/[0.1] bg-[#111827] px-3 text-sm text-slate-200"><option value="">Select Trade Twin</option>{trades.data?.map(trade => <option key={trade.id} value={trade.id}>{trade.reference}</option>)}</select><Input value={booking} onChange={e => setBooking(e.target.value)} placeholder="Booking reference" className="border-white/[0.1] bg-[#111827] text-slate-200" /></div><Button disabled={!canTrade || !tradeId || createShipment.isPending} onClick={() => createShipment.mutate({ tradeId: Number(tradeId), mode: "sea", bookingReference: booking || undefined })} className="mt-3 bg-blue-500 text-white hover:bg-blue-400">Create shipment allocation</Button></div></TabsContent>
      <TabsContent value="settlement" className="mt-5"><div className="panel max-w-3xl p-6"><div className="flex items-center gap-2"><Landmark className="h-4 w-4 text-blue-300" /><p className="text-sm font-semibold text-slate-100">Settlement and finance readiness</p></div><p className="mt-2 text-xs leading-5 text-slate-500">Record payment terms and evidence. ARCWAY evaluates readiness; it does not move money, extend credit, or make lending decisions.</p><div className="mt-5 grid gap-3 md:grid-cols-2"><select value={tradeId} onChange={e => setTradeId(e.target.value)} className="h-10 rounded-md border border-white/[0.1] bg-[#111827] px-3 text-sm text-slate-200"><option value="">Select Trade Twin</option>{trades.data?.map(trade => <option key={trade.id} value={trade.id}>{trade.reference}</option>)}</select><select value={terms} onChange={e => setTerms(e.target.value)} className="h-10 rounded-md border border-white/[0.1] bg-[#111827] px-3 text-sm text-slate-200"><option value="letter_of_credit">Letter of credit</option><option value="advance">Advance</option><option value="open_account">Open account</option><option value="documentary_collection">Documentary collection</option></select></div><Button disabled={!canTrade || !tradeId || updateTerms.isPending} onClick={() => updateTerms.mutate({ tradeId: Number(tradeId), method: terms as "letter_of_credit" | "advance" | "open_account" | "documentary_collection" })} className="mt-3 bg-blue-500 text-white hover:bg-blue-400">Record settlement terms</Button></div></TabsContent>
    </Tabs>
  </div>;
}
