import { PageTitle, StatusBadge } from "@/components/arcway/primitives";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { BadgeAlert, FileClock, RefreshCw, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";

export default function PreflightGovernance() {
  const { user } = useAuth();
  const trades = trpc.trades.list.useQuery(undefined, { retry: false });
  const [tradeId, setTradeId] = useState<number | null>(null);
  const activeId = tradeId ?? trades.data?.[0]?.id ?? null;
  const workspace = trpc.trades.get.useQuery({ tradeId: activeId ?? 0 }, { enabled: Boolean(activeId), retry: false });
  const decision = trpc.trades.preflight.useQuery({ tradeId: activeId ?? 0 }, { enabled: Boolean(activeId), retry: false });
  const utils = trpc.useUtils();
  const [ruleKey, setRuleKey] = useState("");
  const [reason, setReason] = useState("");
  const [expiresAt, setExpiresAt] = useState("");
  const refresh = () => { if (activeId) { utils.trades.get.invalidate({ tradeId: activeId }); utils.trades.preflight.invalidate({ tradeId: activeId }); } };
  const createWaiver = trpc.operations.preflight.createWaiver.useMutation({ onSuccess: () => { toast.success("Governed waiver retained with reviewer authority and expiry"); setRuleKey(""); setReason(""); setExpiresAt(""); refresh(); }, onError: error => toast.error(error.message) });
  const revoke = trpc.operations.preflight.revokeWaiver.useMutation({ onSuccess: () => { toast.success("Waiver revoked"); refresh(); }, onError: error => toast.error(error.message) });
  const rerun = trpc.trades.rerunPreflight.useMutation({ onSuccess: result => { toast.success(`Preflight rerun retained: ${result.summary}`); refresh(); }, onError: error => toast.error(error.message) });
  const data = workspace.data;
  const isReviewer = user?.role === "reviewer";

  return <div className="mx-auto max-w-[1540px] animate-enter"><PageTitle eyebrow="Preflight governance" title="Release only with explainable policy decisions." description="Each rerun stores its complete gate decision, evidence state, release dependencies, policy-waiver context, reviewer identity, and timestamp." />
    <div className="mt-6 grid gap-5 xl:grid-cols-[250px_1fr]"><aside className="panel h-fit overflow-hidden"><div className="border-b border-white/[0.07] px-4 py-3"><p className="text-xs font-semibold uppercase tracking-[0.13em] text-slate-500">Trade Twin</p></div>{trades.data?.map(trade => <button key={trade.id} onClick={() => setTradeId(trade.id)} className={`w-full border-b border-white/[0.05] px-4 py-4 text-left ${activeId === trade.id ? "bg-blue-500/[0.08]" : "hover:bg-white/[0.03]"}`}><p className="font-mono text-[10px] text-blue-300">{trade.reference}</p><p className="mt-1 text-xs text-slate-300">{trade.sellerName} → {trade.buyerName}</p></button>)}</aside>
      {data && <section className="grid gap-5 xl:grid-cols-[0.85fr_1.15fr]"><div className="space-y-5">{isReviewer ? <div className="panel p-6"><div className="flex items-center gap-2"><BadgeAlert className="h-4 w-4 text-amber-300" /><p className="text-sm font-semibold text-slate-100">Record a governed waiver</p></div><p className="mt-2 text-xs leading-5 text-slate-500">A waiver accepts a named policy rule only until its expiry. It does not delete conflicting evidence or resolve the underlying issue.</p><Input value={ruleKey} onChange={event => setRuleKey(event.target.value)} placeholder="Policy rule key, e.g. certificate_of_origin_required" className="mt-5 border-white/[0.1] bg-[#111827] text-slate-200 placeholder:text-slate-600" /><Textarea value={reason} onChange={event => setReason(event.target.value)} placeholder="Reviewer rationale, business boundary, and compensating control…" className="mt-3 min-h-28 border-white/[0.1] bg-[#111827] text-slate-200 placeholder:text-slate-600" /><label className="mt-3 block text-xs text-slate-500">Expiry<Input type="datetime-local" value={expiresAt} onChange={event => setExpiresAt(event.target.value)} className="mt-1 border-white/[0.1] bg-[#111827] text-slate-200" /></label><Button disabled={!ruleKey || reason.length < 12 || !expiresAt || createWaiver.isPending} onClick={() => createWaiver.mutate({ tradeId: data.trade.id, ruleKey, reason, expiresAt: new Date(expiresAt) })} className="mt-4 bg-blue-500 text-white hover:bg-blue-400">Create governed waiver</Button></div> : <div className="panel p-6 text-xs leading-5 text-amber-100">Release waivers and preflight runs are reviewer-controlled. You can review the current release decision and retained history here.</div>}</div>
        <div className="space-y-5"><div className="panel p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-blue-300" /><p className="text-sm font-semibold text-slate-100">Retained preflight runs</p></div><p className="mt-1 text-xs text-slate-500">Current decision: <span className="font-medium text-slate-300">{decision.data?.summary ?? "calculating"}</span>{decision.data?.unresolvedReleaseDependencies ? ` · ${decision.data.unresolvedReleaseDependencies} release dependency blocker(s)` : ""}</p></div>{isReviewer && <Button disabled={rerun.isPending} onClick={() => rerun.mutate({ tradeId: data.trade.id })} className="bg-blue-500 text-white hover:bg-blue-400"><RefreshCw className={`mr-1.5 h-4 w-4 ${rerun.isPending ? "animate-spin" : ""}`} />Rerun preflight</Button>}</div><div className="mt-5 space-y-3">{data.preflightRuns.length ? data.preflightRuns.map(run => { const snapshot = run.policySnapshot as { policyVersions?: Array<{ policyName: string; policyVersionId: number; version: number; scope: string }> } | null; const versions = snapshot?.policyVersions ?? []; return <div key={run.id} className="rounded-lg border border-white/[0.07] bg-white/[0.025] p-4"><div className="flex items-center justify-between gap-3"><p className="text-sm text-slate-200">{run.gate.replaceAll("_", " ")}</p><StatusBadge status={run.status.replaceAll("_", " ")} /></div><p className="mt-2 text-xs text-slate-500">Executed {new Date(run.createdAt).toLocaleString()} · checks, evidence snapshot, policy context, and release decision retained</p><div className="mt-3 flex flex-wrap gap-2">{versions.length ? versions.map(version => <span key={version.policyVersionId} className="rounded-md border border-blue-400/15 bg-blue-400/[0.04] px-2 py-1 text-[10px] text-blue-200">{version.policyName} · v{version.version} · {version.scope}</span>) : <span className="text-[10px] text-slate-600">No active policy configuration existed at this run.</span>}</div></div>; }) : <p className="text-sm text-slate-500">No preflight run retained yet. A reviewer can run the current release decision.</p>}</div></div>
          <div className="panel p-6"><div className="flex items-center gap-2"><FileClock className="h-4 w-4 text-blue-300" /><p className="text-sm font-semibold text-slate-100">Waiver history</p></div><div className="mt-5 space-y-3">{data.preflightWaivers.length ? data.preflightWaivers.map(waiver => <div key={waiver.id} className="rounded-lg border border-white/[0.07] bg-white/[0.025] p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-xs text-blue-200">{waiver.ruleKey}</p><p className="mt-2 text-sm text-slate-300">{waiver.reason}</p><p className="mt-2 text-xs text-slate-500">Approved {new Date(waiver.approvedAt).toLocaleString()} · expires {new Date(waiver.expiresAt).toLocaleString()}</p></div><StatusBadge status={waiver.decision} /></div>{isReviewer && waiver.decision === "active" && <Button disabled={revoke.isPending} onClick={() => revoke.mutate({ waiverId: waiver.id })} variant="outline" className="mt-3 h-8 border-rose-400/20 bg-rose-400/[0.04] text-xs text-rose-200 hover:bg-rose-400/[0.1]">Revoke waiver</Button>}</div>) : <p className="text-sm text-slate-500">No waivers have been recorded for this Trade Twin.</p>}</div></div></div>
      </section>}
    </div>
  </div>;
}
