import { useAuth } from "@/_core/hooks/useAuth";
import { PageTitle } from "@/components/arcway/primitives";
import { trpc } from "@/lib/trpc";
import { aggregateProductExposure } from "@shared/reporting";
import { AlertTriangle, PackageSearch } from "lucide-react";

type Row = { line: { id: number; sku: string | null; description: string; totalValue: string | number | null }; trade: { id: number; reference: string; assuranceState: string; trustBand: string; executionState: string }; product: { sku: string; description: string } | null };
const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);

export default function ProductRiskReporting() {
  const { user } = useAuth(); const isReviewer = user?.role === "reviewer"; const query = trpc.trades.productConcentration.useQuery(undefined, { retry: false, enabled: isReviewer }); const rows = (query.data ?? []) as Row[]; const products = aggregateProductExposure(rows); const total = products.reduce((sum, product) => sum + product.value, 0);
  if (!isReviewer) return <div className="mx-auto max-w-[1440px] animate-enter"><PageTitle eyebrow="Executive product risk" title="Reviewer-controlled product concentration." description="Product concentration aggregates organization-wide trade-line exposure and is restricted to Reviewers." /><div className="panel mt-6 p-6 text-sm leading-6 text-slate-500">Product-risk concentration data is available to Reviewers only. Your Trader workspace continues to provide access to the Trade Twins you own.</div></div>;
  return <div className="mx-auto max-w-[1440px] animate-enter"><PageTitle eyebrow="Executive product risk" title="See product-level concentration from actual Trade Lines and product masters." description="This report aggregates stored trade-line value by linked product or retained line SKU. It distinguishes product exposure from commodity labels and shows associated blocked and critical Trade Twin signals." /><section className="mt-6 flex gap-3 rounded-xl border border-amber-400/20 bg-amber-400/[0.05] p-4 text-sm leading-6 text-amber-100"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" /><p><strong>Observed reporting boundary.</strong> No calibrated prediction model is active. This surface reports retained exposure and current Trade Twin signals only; it does not forecast production delay, booking risk, document rework, or payment delay.</p></section><div className="mt-6 panel overflow-hidden"><div className="border-b border-white/[0.07] px-6 py-4"><div className="flex items-center gap-2"><PackageSearch className="h-4 w-4 text-blue-300" /><p className="text-sm font-semibold text-slate-100">Product concentration</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b border-white/[0.07] text-[10px] uppercase tracking-[0.12em] text-slate-500"><th className="px-6 py-3">Product / trade line</th><th className="px-6 py-3">Assessed value</th><th className="px-6 py-3">Share</th><th className="px-6 py-3">Trades</th><th className="px-6 py-3">Observed risk drivers</th></tr></thead><tbody>{products.map(product => { const share = total ? product.value / total * 100 : 0; return <tr key={product.label} className="border-b border-white/[0.05] last:border-0"><td className="px-6 py-4 text-sm text-slate-200">{product.label}</td><td className="px-6 py-4 font-mono text-xs text-blue-200">{money(product.value)}</td><td className="px-6 py-4"><div className="flex items-center gap-3"><div className="h-1.5 w-24 overflow-hidden rounded-full bg-white/[0.06]"><div className="h-full rounded-full bg-blue-400" style={{ width: `${Math.max(2, Math.min(100, share))}%` }} /></div><span className="text-xs text-slate-400">{share.toFixed(1)}%</span></div></td><td className="px-6 py-4 text-sm text-slate-300">{product.trades}</td><td className="px-6 py-4 text-xs text-slate-400">{product.blocked ? `${product.blocked} blocked` : "No blocked"}{product.critical ? ` · ${product.critical} critical` : ""}</td></tr>; })}{!products.length && <tr><td colSpan={5} className="px-6 py-12 text-center text-sm text-slate-500">No trade lines are available. Add product-linked trade lines to populate product concentration.</td></tr>}</tbody></table></div></div></div>;
}
