import { useAuth } from "@/_core/hooks/useAuth";
import { EmptyPanel, PageTitle, StatusBadge } from "@/components/arcway/primitives";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, FileSpreadsheet, ShieldAlert } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

type MappingPayload = { mappingApplication?: { mappingId?: number; sourceName?: string; mappedPreview?: Array<Record<string, unknown>>; canonicalFieldMap?: Record<string, string> } };

export default function StructuredSourceReview() {
  const { user } = useAuth(); const isReviewer = user?.role === "reviewer"; const operations = trpc.operations.integrations.list.useQuery(undefined, { retry: false, enabled: isReviewer }); const utils = trpc.useUtils();
  const candidates = useMemo(() => (operations.data?.receipts ?? []).filter(receipt => { const raw = (receipt.rawPayload ?? {}) as MappingPayload; return Boolean(raw.mappingApplication?.mappedPreview?.length); }), [operations.data]);
  const [receiptId, setReceiptId] = useState<number | null>(null); const selected = candidates.find(receipt => receipt.id === (receiptId ?? candidates[0]?.id)); const payload = (selected?.rawPayload ?? {}) as MappingPayload; const rows = payload.mappingApplication?.mappedPreview ?? []; const [rowIndex, setRowIndex] = useState(0); const row = rows[rowIndex] ?? {}; const [fieldName, setFieldName] = useState(""); const [rationale, setRationale] = useState("");
  const confirm = trpc.operations.integrations.confirmMappedField.useMutation({ onSuccess: result => { toast.success(`Field confirmed as evidence #${result.evidenceFieldId} and retained in canonical resolution #${result.resolutionId}.`); setRationale(""); utils.operations.integrations.list.invalidate(); }, onError: error => toast.error(error.message) });
  if (!isReviewer) return <div className="mx-auto max-w-2xl"><PageTitle eyebrow="Restricted review" title="Mapped source confirmation is reviewer-controlled." description="Traders can submit and map structured source files. A Reviewer must assess the source preview and retain a rationale before a value enters evidence provenance or canonicalization." /><div className="panel p-6"><ShieldAlert className="h-6 w-6 text-amber-300" /><p className="mt-3 text-sm text-slate-400">Use Source Intake to submit a structured file, then return in the Reviewer workspace to confirm a field.</p></div></div>;
  return <div className="mx-auto max-w-[1440px] animate-enter"><PageTitle eyebrow="Structured source review" title="Confirm mapped source values only with a named reviewer decision." description="CSV and XLSX mappings remain source previews until a reviewer selects one mapped value, records a rationale, and explicitly creates authoritative evidence plus a canonical-resolution trace." />
    <div className="mt-6 grid gap-5 xl:grid-cols-[290px_1fr]"><aside className="panel h-fit overflow-hidden"><div className="border-b border-white/[0.07] px-4 py-3"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-slate-500">Mapped source receipts</p></div>{candidates.length ? candidates.map(receipt => { const itemPayload = (receipt.rawPayload ?? {}) as MappingPayload; return <button key={receipt.id} onClick={() => { setReceiptId(receipt.id); setRowIndex(0); setFieldName(""); }} className={`w-full border-b border-white/[0.06] px-4 py-4 text-left ${selected?.id === receipt.id ? "bg-blue-400/[0.08]" : "hover:bg-white/[0.03]"}`}><div className="flex items-start justify-between gap-2"><p className="text-sm text-slate-200">{receipt.fileName || `Receipt #${receipt.id}`}</p><StatusBadge status={receipt.normalizedStatus} /></div><p className="mt-1 text-xs text-slate-500">{itemPayload.mappingApplication?.sourceName || "Mapped source"} · {itemPayload.mappingApplication?.mappedPreview?.length || 0} preview row(s)</p></button>; }) : <p className="px-4 py-10 text-sm text-slate-500">No mapped source preview is awaiting reviewer confirmation.</p>}</aside>
      {selected ? <section className="space-y-5"><div className="panel p-6"><div className="flex items-start gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-lg border border-blue-400/15 bg-blue-400/[0.06]"><FileSpreadsheet className="h-4 w-4 text-blue-200" /></div><div><p className="text-sm font-semibold text-slate-100">{selected.fileName || `Structured receipt #${selected.id}`}</p><p className="mt-1 text-xs leading-5 text-slate-500">Receipt #{selected.id} · mapping {payload.mappingApplication?.sourceName || "unlabelled"} · source hash {selected.payloadHash?.slice(0, 16) || "not retained"}</p></div></div><div className="mt-5 flex flex-wrap gap-2">{rows.map((_, index) => <button key={index} onClick={() => { setRowIndex(index); setFieldName(""); }} className={`rounded-md border px-3 py-1.5 text-xs ${rowIndex === index ? "border-blue-400/30 bg-blue-400/[0.08] text-blue-200" : "border-white/[0.08] text-slate-400 hover:bg-white/[0.04]"}`}>Preview row {index + 1}</button>)}</div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[640px] text-left"><thead><tr className="border-b border-white/[0.08] text-[10px] uppercase tracking-[0.11em] text-slate-500">{Object.keys(row).map(key => <th key={key} className="px-3 py-3">{key}</th>)}</tr></thead><tbody><tr>{Object.entries(row).map(([key, value]) => <td key={key} className="border-b border-white/[0.05] px-3 py-4 text-sm text-slate-200">{String(value ?? "—")}</td>)}</tr></tbody></table></div></div>
        <div className="panel p-6"><div className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-300" /><p className="text-sm font-semibold text-slate-100">Explicit reviewer confirmation</p></div><p className="mt-2 text-xs leading-5 text-slate-500">This action creates an authoritative evidence field, a canonical-resolution record, a Trade Twin event, and an audit record. It does not alter other mapped fields.</p><div className="mt-5 grid gap-3 md:grid-cols-[0.7fr_1.3fr]"><select value={fieldName} onChange={event => setFieldName(event.target.value)} className="h-11 rounded-lg border border-white/[0.1] bg-[#111827] px-3 text-sm text-slate-200"><option value="">Select mapped field</option>{Object.keys(row).map(key => <option key={key} value={key}>{key}: {String(row[key] ?? "—")}</option>)}</select><Textarea value={rationale} onChange={event => setRationale(event.target.value)} placeholder="Explain why this mapped source value is authoritative and how it was validated against the Trade Twin…" className="min-h-20 border-white/[0.1] bg-[#111827] text-sm text-slate-200 placeholder:text-slate-600" /></div><Button disabled={!fieldName || rationale.trim().length < 12 || confirm.isPending} onClick={() => confirm.mutate({ receiptId: selected.id, rowIndex, fieldName, rationale })} className="mt-4 bg-emerald-500 text-white hover:bg-emerald-400"><CheckCircle2 className="mr-2 h-4 w-4" />Confirm mapped field for canonicalization</Button></div></section> : <EmptyPanel title="No mapped structured source available" description="Upload a CSV/XLSX file and apply a reusable mapping in Source Intake first." />}
    </div>
  </div>;
}
