import { useAuth } from "@/_core/hooks/useAuth";
import { EmptyPanel, PageTitle, StatusBadge, TrustGauge, formatDate, formatMoney } from "@/components/arcway/primitives";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { ArrowDownUp, Filter, Plus, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";

export default function Trades() {
  const { user } = useAuth();
  const query = trpc.trades.list.useQuery(undefined, { retry: false });
  const [search, setSearch] = useState("");
  const [state, setState] = useState("all");
  const [sort, setSort] = useState<"updated" | "value" | "trust">("updated");
  const rows = useMemo(() => (query.data ?? []).filter(trade => (state === "all" || trade.assuranceState === state) && `${trade.reference} ${trade.sellerName} ${trade.buyerName} ${trade.commodity}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => sort === "value" ? Number(b.totalValue) - Number(a.totalValue) : sort === "trust" ? b.trustScore - a.trustScore : +new Date(b.updatedAt) - +new Date(a.updatedAt)), [query.data, search, state, sort]);
  return <div className="mx-auto max-w-[1540px] animate-enter"><PageTitle eyebrow="Trade inbox" title="Every trade. Checked before it moves." description="Search, filter, and prioritize canonical Trade Twins using their current evidence, readiness, and assurance state." action={user?.role === "trader" ? <Link href="/trades/new"><Button className="gap-2 bg-blue-500 text-white hover:bg-blue-400"><Plus className="h-4 w-4" />Create trade</Button></Link> : undefined} />
    <div className="panel overflow-hidden"><div className="flex flex-col gap-3 border-b border-white/[0.07] p-4 lg:flex-row lg:items-center lg:justify-between"><div className="relative max-w-sm flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500" /><Input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search trade, party, commodity" className="h-10 border-white/[0.09] bg-white/[0.035] pl-9 text-slate-200 placeholder:text-slate-600" /></div><div className="flex flex-wrap gap-2"><div className="flex items-center gap-2 rounded-lg border border-white/[0.09] bg-white/[0.025] px-3"><Filter className="h-3.5 w-3.5 text-slate-500" /><select value={state} onChange={event => setState(event.target.value)} className="h-9 bg-transparent text-xs text-slate-300 outline-none"><option value="all">All assurance states</option><option value="draft">Draft</option><option value="submitted">Submitted</option><option value="under_review">Under review</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></div><Button variant="outline" onClick={() => setSort(sort === "updated" ? "value" : sort === "value" ? "trust" : "updated")} className="h-10 border-white/[0.09] bg-white/[0.025] text-slate-300 hover:bg-white/[0.06] hover:text-white"><ArrowDownUp className="mr-2 h-3.5 w-3.5" />Sort: {sort}</Button></div></div>
      {query.isLoading ? <div className="space-y-1 p-4">{Array.from({ length: 5 }).map((_, index) => <Skeleton key={index} className="h-16 bg-white/[0.05]" />)}</div> : rows.length === 0 ? <div className="p-5"><EmptyPanel title={search || state !== "all" ? "No matching trades" : "No Trade Twins yet"} description={search || state !== "all" ? "Try a broader search or another assurance state." : "Create an export order to turn its terms, evidence, and obligations into a verifiable Trade Twin."} action={user?.role === "trader" && !search && state === "all" ? <Link href="/trades/new"><Button className="bg-blue-500 text-white hover:bg-blue-400"><Plus className="mr-2 h-4 w-4" />Create trade</Button></Link> : undefined} /></div> : <div className="overflow-x-auto"><table className="w-full min-w-[880px] text-left"><thead><tr className="border-b border-white/[0.06] text-[10px] font-semibold uppercase tracking-[0.13em] text-slate-500"><th className="px-5 py-3">Trade twin</th><th className="px-5 py-3">Route & commodity</th><th className="px-5 py-3">Shipment</th><th className="px-5 py-3">Evidence</th><th className="px-5 py-3">Assurance</th><th className="px-5 py-3 text-right">Trust</th></tr></thead><tbody>{rows.map(trade => { const verified = trade.documentSummary.filter(doc => doc.status === "verified").length; return <tr key={trade.id} className="border-b border-white/[0.05] transition-colors hover:bg-white/[0.025]"><td className="px-5 py-4"><Link href={`/trades/${trade.id}`}><p className="font-mono text-xs text-blue-300">{trade.reference}</p><p className="mt-1 text-sm font-medium text-slate-200">{trade.sellerName} <span className="text-slate-600">→</span> {trade.buyerName}</p><p className="mt-1 text-xs text-slate-500">{formatMoney(trade.totalValue, trade.currency)}</p></Link></td><td className="px-5 py-4"><p className="text-sm text-slate-300">{trade.commodity}</p><p className="mt-1 text-xs text-slate-500">{trade.originCountry} → {trade.destinationCountry} · {trade.incoterm}</p></td><td className="px-5 py-4 text-xs text-slate-400">{formatDate(trade.expectedShipmentDate)}</td><td className="px-5 py-4"><p className="text-sm font-medium text-slate-300">{verified}/6 verified</p><p className="mt-1 text-xs text-slate-500">Required documents</p></td><td className="px-5 py-4"><StatusBadge status={trade.assuranceState} kind="assurance" /></td><td className="px-5 py-3"><div className="flex justify-end"><TrustGauge score={trade.trustScore} band={trade.trustBand} compact /></div></td></tr>})}</tbody></table></div>}</div></div>;
}

