import { useAuth } from "@/_core/hooks/useAuth";
import { EmptyPanel, PageTitle } from "@/components/arcway/primitives";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowRight, ClipboardCheck, FileWarning, ShieldAlert, Sparkles, Waypoints } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";

type Reason = { kind: "document" | "exception" | "obligation" | "evidence_conflict" | "preflight"; title: string; detail: string; action: string; severity: "critical" | "warning" };
type Explanation = { status: "blocked" | "attention" | "no_retained_blocker" | "insufficient_evidence"; summary: string; reasons: Reason[] };
const destinations: Record<Reason["kind"], string> = { document: "/workbench", exception: "/exception-resolution", obligation: "/obligations", evidence_conflict: "/comparison", preflight: "/preflight-governance" };
const labels: Record<Reason["kind"], string> = { document: "Document Workbench", exception: "Exception Resolution", obligation: "Obligation Control", evidence_conflict: "Comparison Matrix", preflight: "Preflight Governance" };

export default function WhyBlockedCenter() {
  const { user } = useAuth(); const trades = trpc.trades.list.useQuery(undefined, { retry: false }); const [selectedId, setSelectedId] = useState<number | null>(null); const list = trades.data ?? []; const activeId = selectedId ?? list[0]?.id ?? null; const input = useMemo(() => activeId ? { tradeId: activeId } : undefined, [activeId]); const explanation = trpc.operations.assurance.explain.useQuery(input!, { enabled: Boolean(activeId), retry: false }); const data = explanation.data as Explanation | undefined;
  return <div className="mx-auto max-w-[1240px] animate-enter"><PageTitle eyebrow="Assurance explanation" title="See why a Trade Twin needs attention." description="ARCWAY explains only retained conditions: document state, open exceptions and obligations, evidence conflicts, and the latest retained preflight. It does not recalculate a release decision or certify readiness." />
    {!list.length ? <div className="mt-6"><EmptyPanel title="No Trade Twin is available" description="Create or route a Trade Twin before reviewing its retained assurance explanation." action={<Link href="/trades/new"><Button className="bg-blue-500 text-white hover:bg-blue-400">Create Trade Twin</Button></Link>} /></div> : <><section className="mt-6 panel p-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-slate-100">Trade Twin context</p><p className="mt-1 text-xs text-slate-500">The explanation is scoped to the selected Trade Twin and respects workspace ownership.</p></div><select value={activeId ?? ""} onChange={event => setSelectedId(Number(event.target.value))} aria-label="Select Trade Twin for assurance explanation" className="h-10 min-w-[300px] rounded-lg border border-white/[0.1] bg-[#111827] px-3 text-sm text-slate-200">{list.map(trade => <option key={trade.id} value={trade.id}>{trade.reference} · {trade.buyerName} → {trade.sellerName}</option>)}</select></div></section>{explanation.isLoading ? <div className="mt-6 panel p-8 text-sm text-slate-500">Reading retained assurance context…</div> : !data ? <div className="mt-6 panel p-8 text-sm text-rose-200">The retained assurance explanation could not be loaded.</div> : <ExplanationView data={data} />}</>}</div>;
}

function ExplanationView({ data }: { data: Explanation }) {
  const critical = data.reasons.filter(reason => reason.severity === "critical").length; const insufficient = data.status === "insufficient_evidence"; const attention = data.status === "attention" || insufficient; const Icon = data.status === "blocked" ? ShieldAlert : attention ? AlertTriangle : ClipboardCheck; const palette = data.status === "blocked" ? "border-rose-400/20 bg-rose-400/[0.05] text-rose-100" : attention ? "border-amber-400/20 bg-amber-400/[0.05] text-amber-100" : "border-emerald-400/20 bg-emerald-400/[0.05] text-emerald-100"; const emptyTitle = insufficient ? "Insufficient retained assurance evidence" : "No retained blocker was identified"; const emptyDescription = insufficient ? "Add or review retained evidence and run the applicable preflight before relying on this Trade Twin. This is not a release decision." : "This is not a release decision. Run and review preflight before moving goods, documents, or money.";
  return <><section className={`mt-6 rounded-2xl border p-6 ${palette}`}><div className="flex gap-4"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-black/10"><Icon className="h-5 w-5" /></div><div><p className="text-[10px] font-semibold uppercase tracking-[0.14em] opacity-75">{data.status.replaceAll("_", " ")}</p><h2 className="mt-1 text-xl font-semibold tracking-[-0.03em]">{data.summary}</h2><p className="mt-2 max-w-3xl text-sm leading-6 opacity-80">The panel is explanatory. Release still requires the retained preflight, applicable policy, and authorized Reviewer decision.</p></div></div></section><div className="mt-6 grid gap-4 md:grid-cols-3"><Metric icon={ShieldAlert} label="Blocking conditions" value={critical} text="Critical retained reasons" tone="rose" /><Metric icon={Waypoints} label="Attention signals" value={data.reasons.length - critical} text="Warnings needing review" tone="amber" /><Metric icon={Sparkles} label="New facts inferred" value="0" text="Explanation is evidence-led" tone="blue" /></div><section className="mt-6 panel overflow-hidden"><div className="border-b border-white/[0.07] px-5 py-4"><p className="text-sm font-semibold text-slate-100">Retained reasons and next actions</p><p className="mt-1 text-xs text-slate-500">Each action opens the existing workflow that holds the underlying evidence or decision.</p></div>{!data.reasons.length ? <div className="p-6"><EmptyPanel title={emptyTitle} description={emptyDescription} /></div> : <div className="divide-y divide-white/[0.06]">{data.reasons.map((reason, index) => <article key={`${reason.kind}-${index}`} className="grid gap-4 p-5 lg:grid-cols-[minmax(0,1fr)_auto]"><div><div className="flex items-center gap-2"><span className={`rounded-md border px-2 py-1 text-[10px] font-semibold uppercase tracking-[0.1em] ${reason.severity === "critical" ? "border-rose-400/20 bg-rose-400/[0.05] text-rose-200" : "border-amber-400/20 bg-amber-400/[0.05] text-amber-100"}`}>{reason.severity}</span><span className="text-[11px] uppercase tracking-[0.1em] text-slate-600">{reason.kind.replaceAll("_", " ")}</span></div><h3 className="mt-3 text-sm font-semibold text-slate-100">{reason.title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{reason.detail}</p><p className="mt-3 text-xs leading-5 text-blue-200">{reason.action}</p></div><div className="flex items-start"><Link href={destinations[reason.kind]}><Button variant="outline" size="sm" className="border-blue-400/20 bg-blue-400/[0.03] text-blue-200">{labels[reason.kind]}<ArrowRight className="ml-1 h-3.5 w-3.5" /></Button></Link></div></article>)}</div>}</section><div className="mt-4 flex gap-2 rounded-xl border border-white/[0.07] bg-white/[0.02] p-4 text-xs leading-5 text-slate-500"><FileWarning className="mt-0.5 h-4 w-4 shrink-0 text-amber-200" />Why Blocked uses retained operational state only. It is not legal, banking, customs, regulatory, or trade-compliance certification.</div></>;
}

function Metric({ icon: Icon, label, value, text, tone }: { icon: typeof ShieldAlert; label: string; value: string | number; text: string; tone: "rose" | "amber" | "blue" }) { const styles = { rose: "bg-rose-400/[0.08] text-rose-200", amber: "bg-amber-400/[0.08] text-amber-100", blue: "bg-blue-400/[0.08] text-blue-200" }; return <div className="panel p-5"><div className={`grid h-9 w-9 place-items-center rounded-lg ${styles[tone]}`}><Icon className="h-4 w-4" /></div><p className="mt-4 text-2xl font-semibold tracking-[-0.04em] text-slate-100">{value}</p><p className="mt-1 text-sm font-medium text-slate-300">{label}</p><p className="mt-1 text-xs text-slate-600">{text}</p></div>; }
