export type DraftKind = "ask_supplier" | "request_correction" | "notify_buyer" | "ask_forwarder" | "request_bank_clarification";
type DraftContext = { reference: string; buyerName: string; sellerName: string; expectedShipmentDate: Date; kind: DraftKind; focus: string };
const recipientFor: Record<DraftKind, string> = { ask_supplier: "supplier", request_correction: "document owner", notify_buyer: "buyer", ask_forwarder: "forwarder", request_bank_clarification: "bank contact" };
const requestFor: Record<DraftKind, string> = { ask_supplier: "Please confirm the current delivery, cargo-ready, and supporting-document position.", request_correction: "Please provide a corrected document or explain the retained discrepancy.", notify_buyer: "Please review the retained assurance context and confirm whether any commercial instruction changes are required.", ask_forwarder: "Please confirm booking status, relevant cut-offs, and the documentary handoff needed before shipment.", request_bank_clarification: "Please clarify the applicable documentary or settlement requirement before further presentation steps." };

export function buildOperationalMessageDraft(input: DraftContext) {
  const recipient = recipientFor[input.kind]; const focus = input.focus.trim(); const expectedShipment = input.expectedShipmentDate.toISOString().slice(0, 10);
  return { recipientRole: recipient, subject: `[${input.reference}] ${input.kind.replaceAll("_", " ")}: ${focus}`, body: `Hello ${recipient},\n\nRegarding Trade Twin ${input.reference} between ${input.buyerName} and ${input.sellerName}, we need your assistance with the following retained operational context:\n\n${focus}\n\n${requestFor[input.kind]} The current planned shipment date retained in ARCWAY is ${expectedShipment}.\n\nThis is a draft prepared from retained Trade Twin context. It has not been sent. Please review, edit, and use your approved communication channel before sending.\n\nRegards,\nARCWAY Trade Assurance`, delivery: "copy_only" as const, reviewRequired: true as const };
}
